import { parseOpaqueRecordId, type OpaqueRecordId } from './canonicalIdentity.js';

const SERIES = /^pxs_[0-9a-f]{32}$/;
declare const seriesBrand: unique symbol;
export type OpaqueRecurrenceSeriesId = string & { readonly [seriesBrand]: 'OpaqueRecurrenceSeriesId' };
export function parseOpaqueRecurrenceSeriesId(value: string): OpaqueRecurrenceSeriesId { if (!SERIES.test(value)) throw new Error(`Invalid opaque Proxima recurrence-series id: ${value}`); return value as OpaqueRecurrenceSeriesId; }
export function opaqueRecurrenceSeriesIdFromRandomBytes(bytes: Uint8Array): OpaqueRecurrenceSeriesId { if (bytes.length !== 16) throw new Error('Opaque Proxima recurrence-series ids need exactly 16 random bytes.'); return parseOpaqueRecurrenceSeriesId(`pxs_${Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('')}`); }
export type CanonicalRecurrenceWeekday = 'mon'|'tue'|'wed'|'thu'|'fri'|'sat'|'sun';
export type CanonicalRecurrenceEnd = { readonly kind:'never' } | { readonly kind:'until'; readonly until:string } | { readonly kind:'count'; readonly count:number };
export type CanonicalRecurrenceRule = { readonly frequency:'daily'; readonly interval:number; readonly end:CanonicalRecurrenceEnd } | { readonly frequency:'weekly'; readonly interval:number; readonly weekdays:readonly CanonicalRecurrenceWeekday[]; readonly end:CanonicalRecurrenceEnd } | { readonly frequency:'monthly'; readonly interval:number; readonly dayOfMonth:number; readonly end:CanonicalRecurrenceEnd } | { readonly frequency:'yearly'; readonly interval:number; readonly month:number; readonly dayOfMonth:number; readonly end:CanonicalRecurrenceEnd };
function positive(value:number,label:string){if(!Number.isSafeInteger(value)||value<1)throw new Error(`${label} must be a positive safe integer.`);}
function dateValue(value:string,label:string){if(value.trim()===''||!Number.isFinite(Date.parse(value)))throw new Error(`Invalid canonical recurrence ${label}: ${value}`);}
function copyEnd(end:CanonicalRecurrenceEnd):CanonicalRecurrenceEnd { if(end.kind==='never')return {kind:'never'}; if(end.kind==='until'){dateValue(end.until,'until');return {kind:'until',until:end.until};} positive(end.count,'Recurrence count'); return {kind:'count',count:end.count}; }
export function defineCanonicalRecurrenceRule(rule:CanonicalRecurrenceRule):CanonicalRecurrenceRule { positive(rule.interval,'Recurrence interval'); const end=copyEnd(rule.end); switch(rule.frequency){case 'daily':return {frequency:'daily',interval:rule.interval,end}; case 'weekly': if(!rule.weekdays.length)throw new Error('Canonical weekly recurrence needs at least one weekday.'); if(new Set(rule.weekdays).size!==rule.weekdays.length)throw new Error('Canonical weekly recurrence contains a duplicate weekday.'); return {frequency:'weekly',interval:rule.interval,weekdays:[...rule.weekdays],end}; case 'monthly': if(!Number.isInteger(rule.dayOfMonth)||rule.dayOfMonth<1||rule.dayOfMonth>31)throw new Error('Canonical monthly recurrence dayOfMonth must be between 1 and 31.'); return {frequency:'monthly',interval:rule.interval,dayOfMonth:rule.dayOfMonth,end}; case 'yearly': if(!Number.isInteger(rule.month)||rule.month<1||rule.month>12)throw new Error('Canonical yearly recurrence month must be between 1 and 12.'); if(!Number.isInteger(rule.dayOfMonth)||rule.dayOfMonth<1||rule.dayOfMonth>31)throw new Error('Canonical yearly recurrence dayOfMonth must be between 1 and 31.'); return {frequency:'yearly',interval:rule.interval,month:rule.month,dayOfMonth:rule.dayOfMonth,end};} }
export type CanonicalRecurrenceOwnerKind = 'event'|'task';
export interface CanonicalOccurrenceIdentity { readonly seriesId:OpaqueRecurrenceSeriesId; readonly scheduledStart:string; }
export function defineCanonicalOccurrenceIdentity(input:{seriesId:OpaqueRecurrenceSeriesId;scheduledStart:string}):CanonicalOccurrenceIdentity { return {seriesId:parseOpaqueRecurrenceSeriesId(input.seriesId),scheduledStart:(dateValue(input.scheduledStart,'occurrence start'),input.scheduledStart)}; }
export type CanonicalRecurrenceException = {readonly occurrence:CanonicalOccurrenceIdentity;readonly state:'cancelled'} | {readonly occurrence:CanonicalOccurrenceIdentity;readonly state:'rescheduled';readonly startDate:string;readonly deadline:string} | {readonly occurrence:CanonicalOccurrenceIdentity;readonly state:'detached';readonly detachedRecordId:OpaqueRecordId};
function copyException(seriesId:OpaqueRecurrenceSeriesId,e:CanonicalRecurrenceException):CanonicalRecurrenceException { const occurrence=defineCanonicalOccurrenceIdentity(e.occurrence); if(occurrence.seriesId!==seriesId)throw new Error('Canonical recurrence exception belongs to another series.'); if(e.state==='cancelled')return {occurrence,state:'cancelled'}; if(e.state==='detached')return {occurrence,state:'detached',detachedRecordId:parseOpaqueRecordId(e.detachedRecordId)}; dateValue(e.startDate,'exception startDate'); dateValue(e.deadline,'exception deadline'); if(Date.parse(e.deadline)<Date.parse(e.startDate))throw new Error('Canonical recurrence exception deadline precedes its start.'); return {occurrence,state:'rescheduled',startDate:e.startDate,deadline:e.deadline}; }
export interface CanonicalRecurrenceSeries { readonly seriesId:OpaqueRecurrenceSeriesId; readonly ownerKind:CanonicalRecurrenceOwnerKind; readonly ownerRecordId:OpaqueRecordId; readonly rule:CanonicalRecurrenceRule; readonly exceptions:readonly CanonicalRecurrenceException[]; }
export function defineCanonicalRecurrenceSeries(input:{seriesId:OpaqueRecurrenceSeriesId;ownerKind:CanonicalRecurrenceOwnerKind;ownerRecordId:OpaqueRecordId;rule:CanonicalRecurrenceRule;exceptions?:readonly CanonicalRecurrenceException[]}):CanonicalRecurrenceSeries { const seriesId=parseOpaqueRecurrenceSeriesId(input.seriesId); const exceptions=(input.exceptions??[]).map((e)=>copyException(seriesId,e)); const seen=new Set(exceptions.map((e)=>`${e.occurrence.seriesId}:${e.occurrence.scheduledStart}`)); if(seen.size!==exceptions.length)throw new Error('Duplicate canonical recurrence exception'); return {seriesId,ownerKind:input.ownerKind,ownerRecordId:parseOpaqueRecordId(input.ownerRecordId),rule:defineCanonicalRecurrenceRule(input.rule),exceptions}; }
export type CanonicalRecurrenceActionTarget = {readonly scope:'occurrence';readonly occurrence:CanonicalOccurrenceIdentity}|{readonly scope:'series';readonly seriesId:OpaqueRecurrenceSeriesId};
export function defineCanonicalRecurrenceActionTarget(target:CanonicalRecurrenceActionTarget):CanonicalRecurrenceActionTarget { return target.scope==='series'?{scope:'series',seriesId:parseOpaqueRecurrenceSeriesId(target.seriesId)}:{scope:'occurrence',occurrence:defineCanonicalOccurrenceIdentity(target.occurrence)}; }
/**
 * The instant a rule generates for one sequence number, or null when the rule cannot express it.
 *
 * The anchor is the series owner's own start: sequence 0 is the event exactly as it was written, and
 * every later sequence is the rule applied to it. Two callers need this and they must agree — the
 * expansion that draws occurrences and the planner that decides whether an override names a slot the
 * rule actually generates. A planner with its own arithmetic could accept an override for an instant
 * the calendar will never draw, which is how a displayed occurrence becomes a durable one.
 */
export function canonicalOccurrenceStart(anchor:string,rule:CanonicalRecurrenceRule,sequence:number):string|null { const start=Date.parse(anchor); if(!Number.isFinite(start)||!Number.isSafeInteger(sequence)||sequence<0)return null; const amount=sequence*rule.interval; switch(rule.frequency){ case 'daily': return new Date(shiftUtcDays(start,amount)).toISOString(); case 'weekly': return new Date(shiftUtcDays(start,amount*7)).toISOString(); case 'monthly': return shiftUtcMonths(start,amount); case 'yearly': return shiftUtcMonths(start,amount*12); } }

/**
 * The sequence number a start instant belongs to, or null when the rule does not generate it.
 *
 * The inverse of `canonicalOccurrenceStart`, and deliberately computed by *searching* rather than by
 * dividing: month and year lengths make the arithmetic uneven, and a division that is nearly right
 * would accept an instant a day off.
 */
export function canonicalOccurrenceSequence(anchor:string,rule:CanonicalRecurrenceRule,start:string):number|null { if(!Number.isFinite(Date.parse(anchor))||!Number.isFinite(Date.parse(start)))return null; for(let sequence=0;sequence<10_000;sequence+=1){ const candidate=canonicalOccurrenceStart(anchor,rule,sequence); if(candidate===null)return null; if(Date.parse(candidate)===Date.parse(start))return sequence; if(Date.parse(candidate)>Date.parse(start))return null; } return null; }

function shiftUtcDays(milliseconds:number,days:number):number { return milliseconds+days*86_400_000; }
function shiftUtcMonths(milliseconds:number,months:number):string|null { const date=new Date(milliseconds); const targetMonth=date.getUTCMonth()+months; const day=date.getUTCDate(); const shifted=new Date(Date.UTC(date.getUTCFullYear(),targetMonth,1,date.getUTCHours(),date.getUTCMinutes(),date.getUTCSeconds(),date.getUTCMilliseconds())); const daysInTarget=new Date(Date.UTC(shifted.getUTCFullYear(),shifted.getUTCMonth()+1,0)).getUTCDate(); shifted.setUTCDate(Math.min(day,daysInTarget)); return shifted.toISOString(); }