import { describe,expect,it } from 'vitest';
import { CANONICAL_DOMAIN_SCHEMA_VERSION,DOMAIN_INFORMATION_CLASSIFICATION,classificationForDomainInformation } from '../src/domain/canonicalDataOwnership.js';
import { CANONICAL_RECORD_SCHEMA_VERSION,defineCanonicalRecordHeader,opaqueRecordIdFromRandomBytes } from '../src/domain/canonicalIdentity.js';
import { HARD_GATE_A_FIXTURE } from './hardGateAFixture.js';
function oneRecordId(){const b=new Uint8Array(16);b[15]=1;return opaqueRecordIdFromRandomBytes(b);}
describe('HARD GATE A / A10 information ownership',()=>{
 it('closes the pre-storage canonical domain on schema version 2',()=>{const record=defineCanonicalRecordHeader({kind:'task',id:oneRecordId(),name:'Versioned record'});expect(CANONICAL_DOMAIN_SCHEMA_VERSION).toBe(2);expect(CANONICAL_RECORD_SCHEMA_VERSION).toBe(CANONICAL_DOMAIN_SCHEMA_VERSION);expect(record.schemaVersion).toBe(CANONICAL_DOMAIN_SCHEMA_VERSION);});
 it('uses exactly the three A10 information authorities',()=>{expect([...new Set(Object.values(DOMAIN_INFORMATION_CLASSIFICATION).map(e=>e.authority))].sort()).toEqual(['backpack-local-state','canonical-record-data','external-artifact-reference']);});
 it('makes every Backpack-local category disposable and non-semantic',()=>{const local=Object.values(DOMAIN_INFORMATION_CLASSIFICATION).filter(e=>e.authority==='backpack-local-state');expect(local.length).toBeGreaterThan(0);expect(local.every(e=>e.durability==='disposable'&&e.domainSemantic===false)).toBe(true);});
 it('allows no canonical domain semantic to survive only as local state',()=>{expect(Object.entries(DOMAIN_INFORMATION_CLASSIFICATION).filter(([,e])=>e.domainSemantic&&e.authority!=='canonical-record-data')).toEqual([]);});
 it('classifies canonical semantics, local presentation and external references separately',()=>{expect(classificationForDomainInformation('task.execution-state')).toEqual({authority:'canonical-record-data',durability:'durable',domainSemantic:true});expect(classificationForDomainInformation('schema.presentation')).toEqual({authority:'backpack-local-state',durability:'disposable',domainSemantic:false});expect(classificationForDomainInformation('external-artifact.identity-and-locator')).toEqual({authority:'external-artifact-reference',durability:'durable',domainSemantic:false});});
 it('includes a fixture where one project simultaneously owns a task and an event',()=>{const {project,task,event}=HARD_GATE_A_FIXTURE.combinedProject;expect(task.projectId).toBe(project.id);expect(event.projectId).toBe(project.id);expect(task.kind).toBe('task');expect(event.kind).toBe('event');});
 it('includes a fixture proving execution and workflow movement remain independent',()=>{const {original,reviewStage,doneStage,executionMoved,workflowMoved}=HARD_GATE_A_FIXTURE.independentTaskMovement;expect(original.executionState).toBe('running');expect(original.workflowStageId).toBe(reviewStage.id);expect(executionMoved.executionState).toBe('finished');expect(executionMoved.workflowStageId).toBe(original.workflowStageId);expect(workflowMoved.workflowStageId).toBe(doneStage.id);expect(workflowMoved.executionState).toBe(original.executionState);});
});
