import { describe, expect, it } from 'vitest';
import { defineCanonicalRecordHeader, defineLegacyImportProvenance, opaqueRecordIdFromRandomBytes, pairCanonicalWithLegacyProvenance, parseOpaqueRecordId, type OpaqueRecordId } from '../src/domain/canonicalIdentity.js';
import { defineCanonicalOccurrenceIdentity, defineCanonicalRecurrenceActionTarget, defineCanonicalRecurrenceRule, defineCanonicalRecurrenceSeries, opaqueRecurrenceSeriesIdFromRandomBytes, parseOpaqueRecurrenceSeriesId, type OpaqueRecurrenceSeriesId } from '../src/domain/canonicalRecurrence.js';
function recordId(value:number):OpaqueRecordId{const b=new Uint8Array(16);b[15]=value;return opaqueRecordIdFromRandomBytes(b);} function seriesId(value:number):OpaqueRecurrenceSeriesId{const b=new Uint8Array(16);b[15]=value;return opaqueRecurrenceSeriesIdFromRandomBytes(b);}
describe('HARD GATE A / A9 canonical recurrence',()=>{
 it('represents recurrence rules as closed typed domain structures',()=>{expect(defineCanonicalRecurrenceRule({frequency:'weekly',interval:2,weekdays:['tue','thu'],end:{kind:'count',count:8}})).toEqual({frequency:'weekly',interval:2,weekdays:['tue','thu'],end:{kind:'count',count:8}});expect(()=>defineCanonicalRecurrenceRule({frequency:'daily',interval:0,end:{kind:'never'}})).toThrow(/positive safe integer/);});
 it('gives the recurrence series explicit identity separate from its owner record',()=>{const ownerRecordId=recordId(1), recurrenceSeriesId=seriesId(1), series=defineCanonicalRecurrenceSeries({seriesId:recurrenceSeriesId,ownerKind:'event',ownerRecordId,rule:{frequency:'daily',interval:1,end:{kind:'never'}}});expect(series.seriesId).toBe(recurrenceSeriesId);expect(series.ownerRecordId).toBe(ownerRecordId);expect(series.seriesId).not.toBe(ownerRecordId);expect(series.seriesId).toMatch(/^pxs_/);expect(series.ownerRecordId).toMatch(/^pxr_/);expect(()=>parseOpaqueRecordId(series.seriesId)).toThrow();expect(()=>parseOpaqueRecurrenceSeriesId(ownerRecordId)).toThrow();});
 it('addresses an ordinary occurrence semantically without materializing a record',()=>{const occurrence=defineCanonicalOccurrenceIdentity({seriesId:seriesId(2),scheduledStart:'2026-09-15T09:00:00.000Z'});expect(occurrence).toEqual({seriesId:occurrence.seriesId,scheduledStart:'2026-09-15T09:00:00.000Z'});expect(occurrence).not.toHaveProperty('recordId');expect(occurrence).not.toHaveProperty('filename');expect(occurrence).not.toHaveProperty('sourcePath');});
 it('makes exception identity and state explicit on the addressed occurrence',()=>{const sid=seriesId(3),cancelled=defineCanonicalOccurrenceIdentity({seriesId:sid,scheduledStart:'2026-09-16T09:00:00.000Z'}),rescheduled=defineCanonicalOccurrenceIdentity({seriesId:sid,scheduledStart:'2026-09-17T09:00:00.000Z'});const series=defineCanonicalRecurrenceSeries({seriesId:sid,ownerKind:'event',ownerRecordId:recordId(3),rule:{frequency:'daily',interval:1,end:{kind:'never'}},exceptions:[{occurrence:cancelled,state:'cancelled'},{occurrence:rescheduled,state:'rescheduled',startDate:'2026-09-17T11:00:00.000Z',deadline:'2026-09-17T12:00:00.000Z'}]});expect(series.exceptions).toEqual([{occurrence:cancelled,state:'cancelled'},{occurrence:rescheduled,state:'rescheduled',startDate:'2026-09-17T11:00:00.000Z',deadline:'2026-09-17T12:00:00.000Z'}]);});
 it('makes this-occurrence versus entire-series scope explicit and source-independent',()=>{const sid=seriesId(4),occurrence=defineCanonicalOccurrenceIdentity({seriesId:sid,scheduledStart:'2026-09-18T09:00:00.000Z'}),a=defineCanonicalRecurrenceActionTarget({scope:'occurrence',occurrence}),b=defineCanonicalRecurrenceActionTarget({scope:'series',seriesId:sid});expect(a).toEqual({scope:'occurrence',occurrence});expect(b).toEqual({scope:'series',seriesId:sid});for(const target of [a,b]){expect(target).not.toHaveProperty('filename');expect(target).not.toHaveProperty('path');expect(target).not.toHaveProperty('sourcePath');}});
 it('keeps recurrence scope stable when a legacy human-facing source moves',()=>{const owner=defineCanonicalRecordHeader({kind:'event',id:recordId(5),name:'Recurring event'}),sid=seriesId(5),occurrence=defineCanonicalOccurrenceIdentity({seriesId:sid,scheduledStart:'2026-09-19T09:00:00.000Z'}),target=defineCanonicalRecurrenceActionTarget({scope:'occurrence',occurrence}),before=pairCanonicalWithLegacyProvenance(owner,defineLegacyImportProvenance('Proxima/events/Recurring event.md',[{value:'legacy-recurring-event',origin:'frontmatter'}])),after=pairCanonicalWithLegacyProvenance(owner,defineLegacyImportProvenance('Archive/renamed/Completely different file.md',[{value:'legacy-recurring-event',origin:'frontmatter'}]));expect(before.provenance.sourcePath).not.toBe(after.provenance.sourcePath);expect(before.record.id).toBe(after.record.id);expect(target).toEqual({scope:'occurrence',occurrence});});
 it('represents a detached special occurrence without changing series identity',()=>{const sid=seriesId(6),ownerRecordId=recordId(6),detachedRecordId=recordId(7),occurrence=defineCanonicalOccurrenceIdentity({seriesId:sid,scheduledStart:'2026-09-20T09:00:00.000Z'}),series=defineCanonicalRecurrenceSeries({seriesId:sid,ownerKind:'event',ownerRecordId,rule:{frequency:'weekly',interval:1,weekdays:['sun'],end:{kind:'never'}},exceptions:[{occurrence,state:'detached',detachedRecordId}]});expect(series.seriesId).toBe(sid);expect(series.ownerRecordId).toBe(ownerRecordId);expect(series.exceptions).toEqual([{occurrence,state:'detached',detachedRecordId}]);expect(detachedRecordId).not.toBe(ownerRecordId);expect(occurrence.seriesId).toBe(series.seriesId);});
});
