import { describe, expect, it } from 'vitest';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import { createVaultMutationCoordinator } from '../src/app/vaultMutation.js';
import { createMemoryRecoveryStore } from '../src/app/vaultRecovery.js';
import { loadVaultState } from '../src/app/vaultRepository.js';
import { promoteEventIdentity } from '../src/app/eventIdentityPromotion.js';

function readerFor(vault: ReturnType<typeof createMemoryVault>) { return { ...vault, readBinary: async (path: string, maxBytes: number) => { const file = await vault.read(path); const bytes = new TextEncoder().encode(file.text); if (bytes.byteLength > maxBytes) throw new Error('large'); return { ...file, bytes }; } }; }
function event(id: string, path: string, revision: string, idOrigin: 'filename' | 'frontmatter') { return { id, source: { path, revision, kind: 'event' as const, idOrigin } }; }
const source = '---\nname: Event\nproject: p\nstartDate: 2026-09-01\ndeadline: 2026-09-02\nisCompleted: false\nforeign: &x value\n---\nbody\n';

describe('13.2M legacy event identity promotion', () => {
  it('promotes filename-derived identity and preserves event semantics', async () => {
    const vault = createMemoryVault({ 'Proxima/events/01.md': source, 'Proxima/events/null.md': source }); const reader = readerFor(vault); const recovery = createMemoryRecoveryStore({ now: () => 0 }); const coordinator = createVaultMutationCoordinator({ reader, writer: vault, recovery });
    let observed = await reader.read('Proxima/events/01.md'); expect(await promoteEventIdentity({ event: event('01', observed.path, observed.revision, 'filename'), reader, coordinator })).toMatchObject({ ok: true }); observed = await reader.read('Proxima/events/null.md'); expect(await promoteEventIdentity({ event: event('null', observed.path, observed.revision, 'filename'), reader, coordinator })).toMatchObject({ ok: true });
    const loaded = (await loadVaultState(reader)).state.events; expect(loaded.find((e) => e.id === '01')).toMatchObject({ id: '01', projectId: 'p', startDate: '2026-09-01', deadline: '2026-09-02', isCompleted: false, source: { idOrigin: 'frontmatter', path: 'Proxima/events/01.md' } }); expect((await reader.read('Proxima/events/null.md')).text).toContain('id: "null"\n'); expect(recovery.list().every((e) => e.status === 'committed')).toBe(true);
  });
  it('frontmatter is a no-op and mismatched/fabricated provenance refuses before reads', async () => { const vault = createMemoryVault({ 'Proxima/events/e1.md': source }); let reads = 0; const base = readerFor(vault); const reader = { ...base, readBinary: async (path: string, maxBytes: number) => { reads += 1; return base.readBinary(path, maxBytes); } }; const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); const rev = (await reader.read('Proxima/events/e1.md')).revision; expect(await promoteEventIdentity({ event: event('e1', 'Proxima/events/e1.md', rev, 'frontmatter'), reader, coordinator })).toMatchObject({ ok: true, noOp: true }); expect(await promoteEventIdentity({ event: event('wrong', 'Proxima/events/e1.md', rev, 'filename'), reader, coordinator })).toMatchObject({ ok: false, reason: 'identity-mismatch' }); expect(await promoteEventIdentity({ event: event('x', 'Proxima/tasks/x.md', rev, 'filename'), reader, coordinator })).toMatchObject({ ok: false, reason: 'invalid-provenance' }); expect(reads).toBe(0); });
  it('malformed and stale promotion fail closed', async () => { const vault = createMemoryVault({ 'Proxima/events/bad.md': 'body', 'Proxima/events/dup.md': '---\nid: one\nid: two\n---\nbody', 'Proxima/events/stale.md': source }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let rev = (await reader.read('Proxima/events/bad.md')).revision; expect(await promoteEventIdentity({ event: event('bad', 'Proxima/events/bad.md', rev, 'filename'), reader, coordinator })).toMatchObject({ ok: false, reason: 'no-frontmatter' }); rev = (await reader.read('Proxima/events/dup.md')).revision; expect(await promoteEventIdentity({ event: event('dup', 'Proxima/events/dup.md', rev, 'filename'), reader, coordinator })).toMatchObject({ ok: false, reason: 'target-ambiguous' }); const old = await reader.read('Proxima/events/stale.md'); vault.set(old.path, '---\nname: peer\n---\npeer'); expect(await promoteEventIdentity({ event: event('stale', old.path, old.revision, 'filename'), reader, coordinator })).toMatchObject({ ok: false, reason: 'stale' }); expect((await vault.read(old.path)).text).toContain('name: peer'); });
});
