import { describe, expect, it } from 'vitest';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import { createVaultMutationCoordinator } from '../src/app/vaultMutation.js';
import { createEvent } from '../src/app/eventCreation.js';
import { loadVaultState } from '../src/app/vaultRepository.js';
function coordinator(vault: ReturnType<typeof createMemoryVault>) { return createVaultMutationCoordinator({ reader: vault, writer: vault }); }
describe('13.2P canonical event creation', () => {
  it('creates and reloads supplied event semantics with deadline fallback', async () => { const vault = createMemoryVault({}); const result = await createEvent({ coordinator: coordinator(vault), input: { id: '01', name: 'New Event', createdAt: '2026-09-08', project: 'p', startDate: '2026-09-09', isCompleted: false, body: '# Body\n' } }); expect(result).toMatchObject({ ok: true, path: 'Proxima/events/01.md' }); expect((await vault.read('Proxima/events/01.md')).text).toContain('id: "01"\n'); expect((await loadVaultState(vault)).state.events[0]).toMatchObject({ id: '01', name: 'New Event', projectId: 'p', startDate: '2026-09-09', deadline: '2026-09-09', isCompleted: false, description: '# Body' }); });
  it('quotes YAML-sensitive values and emits only supplied optionals', async () => { const vault = createMemoryVault({}); expect(await createEvent({ coordinator: coordinator(vault), input: { id: 'null', name: 'null', createdAt: '2026-09-08', project: 'null' } })).toMatchObject({ ok: true }); const text = (await vault.read('Proxima/events/null.md')).text; expect(text).toContain('name: "null"'); expect(text).toContain('project: "null"'); expect(text).not.toContain('startDate:'); });
  it('validates before coordinator and preserves exclusive create races', async () => { const vault = createMemoryVault({}); let calls = 0; const base = coordinator(vault); const spy = { execute: async (...args: Parameters<typeof base.execute>) => { calls += 1; return base.execute(...args); }, events: base.events }; expect(await createEvent({ coordinator: spy, input: { id: '../escape', name: 'x', createdAt: '2026-09-08' } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(await createEvent({ coordinator: spy, input: { id: 'CON.txt', name: 'x', createdAt: '2026-09-08' } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(await createEvent({ coordinator: spy, input: { id: 'bad', name: 'x', createdAt: 'bad' } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(calls).toBe(0); const existing = createMemoryVault({ 'Proxima/events/e.md': 'creator' }); expect(await createEvent({ coordinator: coordinator(existing), input: { id: 'e', name: 'mine', createdAt: '2026-09-08' } })).toMatchObject({ ok: false, reason: 'already-exists' }); expect((await existing.read('Proxima/events/e.md')).text).toBe('creator'); });
});
