import { describe, expect, it } from 'vitest';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import { createVaultMutationCoordinator } from '../src/app/vaultMutation.js';
import { loadVaultState } from '../src/app/vaultRepository.js';
import { updateEventDescription } from '../src/app/eventDescriptionMutation.js';

function readerFor(vault: ReturnType<typeof createMemoryVault>) { return { ...vault, readBinary: async (path: string, maxBytes: number) => { const file = await vault.read(path); const bytes = new TextEncoder().encode(file.text); if (bytes.byteLength > maxBytes) throw new Error('large'); return { ...file, bytes }; } }; }
function event(revision: string, path = 'Proxima/events/e1.md') { return { id: 'e1', source: { path, revision, kind: 'event' as const, idOrigin: 'frontmatter' as const } }; }
const source = '---\r\nid: e1\r\nname: Event\r\nproject: p\r\nstartDate: 2026-09-01\r\ndeadline: 2026-09-02\r\nisCompleted: false\r\ndescription: Old # keep\r\nforeign: &x value\r\n---\r\nbody fallback\r\n';

describe('13.2N event description override/body fallback', () => {
  it('sets then uses body while preserving event fields and bytes', async () => {
    const vault = createMemoryVault({ 'Proxima/events/e1.md': source }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let observed = await reader.read('Proxima/events/e1.md');
    expect(await updateEventDescription({ event: event(observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'set', value: 'New description' } })).toMatchObject({ ok: true }); observed = await reader.read(observed.path); expect((await loadVaultState(reader)).state.events.find((e) => e.id === 'e1')).toMatchObject({ description: 'New description', projectId: 'p', startDate: '2026-09-01', deadline: '2026-09-02' });
    expect(await updateEventDescription({ event: event(observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'use-body' } })).toMatchObject({ ok: true }); const text = (await reader.read(observed.path)).text; expect(text).not.toContain('description:'); expect(text).toContain('foreign: &x value\r\n---\r\nbody fallback\r\n'); expect((await loadVaultState(reader)).state.events.find((e) => e.id === 'e1')).toMatchObject({ description: 'body fallback' });
  });
  it('inserts missing description and missing use-body is a no-op', async () => { const vault = createMemoryVault({ 'Proxima/events/e1.md': '---\nid: e1\nname: Event\n---\nbody' }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let observed = await reader.read('Proxima/events/e1.md'); expect(await updateEventDescription({ event: event(observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'set', value: 'Inserted' } })).toMatchObject({ ok: true }); observed = await reader.read(observed.path); expect((await loadVaultState(reader)).state.events.find((e) => e.id === 'e1')).toMatchObject({ description: 'Inserted' }); expect(await updateEventDescription({ event: event(observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'use-body' } })).toMatchObject({ ok: true }); });
  it('refuses invalid kinds, empty values, block scalars and out-of-scope provenance before reads', async () => { const vault = createMemoryVault({ 'Proxima/events/e1.md': source }); let reads = 0; const base = readerFor(vault); const reader = { ...base, readBinary: async (path: string, maxBytes: number) => { reads += 1; return base.readBinary(path, maxBytes); } }; const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); const rev = (await reader.read('Proxima/events/e1.md')).revision; const common = { event: event(rev), path: 'Proxima/events/e1.md', reader, coordinator }; expect(await updateEventDescription({ ...common, mutation: { kind: 'clear' as never } })).toMatchObject({ ok: false, reason: 'field-not-allowed' }); expect(await updateEventDescription({ ...common, mutation: { kind: 'set', value: '' } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(await updateEventDescription({ ...common, event: event(rev, 'Proxima/tasks/e1.md'), mutation: { kind: 'use-body' } })).toMatchObject({ ok: false, reason: 'invalid-provenance' }); expect(reads).toBe(0); vault.set('Proxima/events/e1.md', '---\nid: e1\ndescription: |\n  block\n---\nbody'); const blockRev = (await reader.read('Proxima/events/e1.md')).revision; expect(await updateEventDescription({ ...common, event: event(blockRev), mutation: { kind: 'use-body' } })).toMatchObject({ ok: false, reason: 'target-unsupported' }); });
});
