import { describe, expect, it } from 'vitest';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import { createVaultMutationCoordinator } from '../src/app/vaultMutation.js';
import { loadVaultState } from '../src/app/vaultRepository.js';
import { updateProjectLinkedFolders } from '../src/app/projectLinkedFoldersMutation.js';
function readerFor(vault: ReturnType<typeof createMemoryVault>) { return { ...vault, readBinary: async (path: string, maxBytes: number) => { const file = await vault.read(path); const bytes = new TextEncoder().encode(file.text); if (bytes.byteLength > maxBytes) throw new Error('large'); return { ...file, bytes }; } }; }
function project(path: string, revision: string) { return { id: path.includes('folder') ? 'folder' : 'p1', source: { path, revision, kind: 'project' as const, idOrigin: 'frontmatter' as const } }; }
describe('13.2R preferred linkedFolders set/clear', () => {
  it('sets and clears preferred inline lists on flat and folder/index projects', async () => { const vault = createMemoryVault({ 'Proxima/projects/p1.md': '---\nid: p1\nname: P\nstatus: active\nprojectType: task\n---\nbody', 'Proxima/projects/folder/index.md': '---\nid: folder\nname: F\nstatus: active\nprojectType: task\n---\nbody' }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let observed = await reader.read('Proxima/projects/p1.md'); expect(await updateProjectLinkedFolders({ project: project(observed.path, observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'set', folders: [{ path: 'Notes' }, { path: 'Drawings', name: 'Art' }] } })).toMatchObject({ ok: true }); expect((await loadVaultState(reader)).state.projects.find((p) => p.id === 'p1')).toMatchObject({ linkedFolders: [{ path: 'Notes', name: 'Notes' }, { path: 'Drawings', name: 'Art' }] }); observed = await reader.read(observed.path); expect(await updateProjectLinkedFolders({ project: project(observed.path, observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'clear' } })).toMatchObject({ ok: true }); observed = await reader.read('Proxima/projects/folder/index.md'); expect(await updateProjectLinkedFolders({ project: project(observed.path, observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'set', folders: [{ path: 'FolderNotes', name: 'Notes' }] } })).toMatchObject({ ok: true }); expect((await loadVaultState(reader)).state.projects.find((p) => p.id === 'folder')).toMatchObject({ linkedFolders: [{ path: 'FolderNotes', name: 'Notes' }] }); });
  it('preserves unrelated bytes and rejects legacy/mixed/duplicate inputs', async () => { const source = '---\r\nid: p1\r\nname: P\r\nlinkedFolders: ["Old"] # keep\r\nforeign: &x value\r\n---\r\nbody\r\n'; const vault = createMemoryVault({ 'Proxima/projects/p1.md': source, 'Proxima/projects/legacy.md': '---\nlinkedFolder: Notes\n---\nbody', 'Proxima/projects/packed.md': '---\nlinkedFolders: Art|Drawings/Art\n---\nbody' }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let observed = await reader.read('Proxima/projects/p1.md'); expect(await updateProjectLinkedFolders({ project: project(observed.path, observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'set', folders: [{ path: 'New' }] } })).toMatchObject({ ok: true }); const text = (await reader.read(observed.path)).text; expect(text).toContain('foreign: &x value\r\n'); expect(text).toContain('---\r\nbody\r\n'); expect((await loadVaultState(reader)).state.projects.find((p) => p.id === 'p1')?.linkedFolders).toMatchObject([{ path: 'New' }]); for (const path of ['Proxima/projects/legacy.md', 'Proxima/projects/packed.md']) { const f = await reader.read(path); expect(await updateProjectLinkedFolders({ project: project(path, f.revision), path, reader, coordinator, mutation: { kind: 'clear' } })).toMatchObject({ ok: false }); } });
  it('refuses invalid values before reads and stale peers preserve bytes', async () => { const vault = createMemoryVault({ 'Proxima/projects/p1.md': '---\nid: p1\nname: P\n---\nbody' }); let reads = 0; const base = readerFor(vault); const reader = { ...base, readBinary: async (path: string, maxBytes: number) => { reads += 1; return base.readBinary(path, maxBytes); } }; const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); const rev = (await reader.read('Proxima/projects/p1.md')).revision; const common = { project: project('Proxima/projects/p1.md', rev), path: 'Proxima/projects/p1.md', reader, coordinator }; expect(await updateProjectLinkedFolders({ ...common, mutation: { kind: 'set', folders: [{ path: 'x' }, { path: 'x' }] } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(await updateProjectLinkedFolders({ ...common, mutation: { kind: 'set', folders: [{ path: '' }] } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(reads).toBe(0); const old = await base.read('Proxima/projects/p1.md'); vault.set(old.path, '---\nid: p1\nname: peer\n---\npeer'); expect(await updateProjectLinkedFolders({ ...common, mutation: { kind: 'set', folders: [{ path: 'mine' }] } })).toMatchObject({ ok: false, reason: 'stale' }); expect((await vault.read(old.path)).text).toContain('name: peer'); });
});
