// @vitest-environment happy-dom
import { beforeEach, describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadProjectNotePreview, loadProjectNotesTree } from '../src/app/projectNotes.js';
import { bindProjectNotesInteractions, EMPTY_PROJECT_NOTES_VIEW, PROJECT_NOTE_WRITE_REFUSAL, renderProjectNotes, type ProjectNotesViewState } from '../src/browser/projectNotes.js';
import { createInteractionHarness } from '../src/browser/interactionHarness.js';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import type { Project } from '../src/domain/types.js';
import { sourceRef } from './fixtures.js';
const project:Project={id:'notes-project',source:sourceRef('project','notes-project'),name:'Notes Project',description:'Detailed linked notes',createdAt:'2026-09-01T00:00:00.000Z',status:'active',projectType:'task',linkedFolders:[{name:'Research',path:'Projects/Notes/Research'}]};
const notesVault=()=>createMemoryVault({'Projects/Notes/Research/root.md':'# Root','Projects/Notes/Research/Nested/child.md':'# Child','Projects/Notes/Research/Nested/board.canvas':JSON.stringify({nodes:[{id:'n1',type:'text',text:'Alpha'},{id:'n2',type:'file',file:'Beta.md'}],edges:[{id:'e1',fromNode:'n1',toNode:'n2'}]}),'Projects/Notes/Research/sketch.excalidraw':JSON.stringify({type:'excalidraw',version:2,elements:[],appState:{},files:{}}),'Outside/secret.md':'# Secret'});
const ready=(tree:Awaited<ReturnType<typeof loadProjectNotesTree>>):ProjectNotesViewState=>({...EMPTY_PROJECT_NOTES_VIEW,projectId:project.id,sourceGeneration:1,treeStatus:'ready',tree,expandedPaths:['Projects/Notes/Research']});
beforeEach(()=>{document.body.innerHTML='';});
describe('Stage 5 slice 5 detailed Notes tree and preview interactions',()=>{
 it('builds a deterministic recursive tree only beneath linked roots',async()=>{const t=await loadProjectNotesTree(notesVault(),project);expect(t.fileCount).toBe(4);expect(t.roots[0]?.entries.map(e=>[e.kind,e.path])).toEqual([['directory','Projects/Notes/Research/Nested'],['file','Projects/Notes/Research/Nested/board.canvas'],['file','Projects/Notes/Research/Nested/child.md'],['file','Projects/Notes/Research/root.md'],['file','Projects/Notes/Research/sketch.excalidraw']]);expect(t.roots[0]?.entries.some(e=>e.path.includes('Outside'))).toBe(false);});
 it('previews Markdown, Canvas and Excalidraw',async()=>{const r=notesVault();const m=await loadProjectNotePreview(r,'Projects/Notes/Research/root.md');expect(m.preview?.kind).toBe('markdown');const c=await loadProjectNotePreview(r,'Projects/Notes/Research/Nested/board.canvas');expect(c.preview?.kind).toBe('canvas');if(c.preview?.kind==='canvas'){expect(c.preview.nodeCount).toBe(2);expect(c.preview.edgeCount).toBe(1);}const e=await loadProjectNotePreview(r,'Projects/Notes/Research/sketch.excalidraw');expect(e.preview?.kind).toBe('excalidraw');});
 it('fails closed for unsafe roots and unsupported previews',async()=>{const t=await loadProjectNotesTree(notesVault(),{...project,linkedFolders:[{name:'Unsafe',path:'../Outside'},{name:'Missing',path:'Projects/Notes/Missing'}]});expect(t.roots.map(r=>r.status)).toEqual(['unavailable','missing']);expect((await loadProjectNotePreview(notesVault(),'../Outside/secret.md')).failure).toBe('invalid-path');expect((await loadProjectNotePreview(createMemoryVault({'Projects/Notes/Research/file.txt':'x'}),'Projects/Notes/Research/file.txt')).failure).toBe('unsupported-format');});
 it('keeps local selection/context and write controls unavailable',async()=>{const tree=await loadProjectNotesTree(notesVault(),project);let view=ready(tree);const render=()=>{document.body.innerHTML=renderProjectNotes(project,view);};render();bindProjectNotesInteractions(document.body,{toggleFolder:()=>{},selectFile:p=>{view={...view,selectedPath:p};render();},openContext:p=>{view={...view,contextPath:p};render();},closeContext:()=>{view={...view,contextPath:null};render();},startDrag:()=>{},previewDrag:()=>{},refuseDrop:()=>{},clearDrag:()=>{}});const h=createInteractionHarness(document);const p='Projects/Notes/Research/root.md';h.click('project-note-file-'+project.id+'-'+p);expect(view.selectedPath).toBe(p);h.contextMenu('project-note-file-'+project.id+'-'+p);const controls=Array.from(document.querySelectorAll<HTMLButtonElement>('[data-project-note-write-action]'));expect(controls).toHaveLength(3);expect(controls.every(c=>c.disabled&&c.dataset.projectNoteWriteRefusal===PROJECT_NOTE_WRITE_REFUSAL)).toBe(true);h.escape('project-note-file-'+project.id+'-'+p);expect(view.contextPath).toBeNull();});
 it('previews drag destination and refuses drop',async()=>{const tree=await loadProjectNotesTree(notesVault(),project);let view=ready(tree);let refused:null|{sourcePath:string;targetPath:string}=null;const render=()=>{document.body.innerHTML=renderProjectNotes(project,view);};render();bindProjectNotesInteractions(document.body,{toggleFolder:()=>{},selectFile:()=>{},openContext:()=>{},closeContext:()=>{},startDrag:p=>{view={...view,dragSourcePath:p};},previewDrag:(s,t)=>{view={...view,dragSourcePath:s,dragTargetPath:t};},refuseDrop:(s,t)=>{refused={sourcePath:s,targetPath:t};view={...view,writeRefusal:PROJECT_NOTE_WRITE_REFUSAL,lastRefusedMove:{sourcePath:s,targetPath:t}};render();},clearDrag:()=>{}});const h=createInteractionHarness(document);const s='Projects/Notes/Research/root.md',t='Projects/Notes/Research/Nested';const d=h.beginDrag('project-note-file-'+project.id+'-'+s,{clientX:0,clientY:0});d.move('project-note-folder-'+project.id+'-'+t,{clientX:1,clientY:1});expect(document.querySelector<HTMLElement>('[data-project-workspace-panel=\"notes\"]')?.dataset.projectNoteDragPreview).toBe(s+' -> '+t);d.drop('project-note-folder-'+project.id+'-'+t,{clientX:1,clientY:1});expect(refused).toEqual({sourcePath:s,targetPath:t});});
 it('expands and collapses linked roots and nested folders without selecting a file',async()=>{
  const tree=await loadProjectNotesTree(notesVault(),project);
  let view:ProjectNotesViewState={...ready(tree),expandedPaths:[]};
  const toggles:string[]=[];
  const host=document.createElement('div');document.body.append(host);const render=()=>{host.innerHTML=renderProjectNotes(project,view);};
  render();
  bindProjectNotesInteractions(host,{toggleFolder:path=>{toggles.push(path);view={...view,expandedPaths:view.expandedPaths.includes(path)?view.expandedPaths.filter(open=>open!==path):[...view.expandedPaths,path]};render();},selectFile:()=>{throw new Error('expanding a folder must not select a file');},openContext:()=>{},closeContext:()=>{},startDrag:()=>{},previewDrag:()=>{},refuseDrop:()=>{},clearDrag:()=>{}});
  const h=createInteractionHarness(host);
  const rootKey='project-note-root-'+project.id+'-Projects/Notes/Research';
  const nestedKey='project-note-folder-'+project.id+'-Projects/Notes/Research/Nested';
  const aria=()=>host.querySelector<HTMLElement>('[data-c1-key="'+rootKey+'"]')?.getAttribute('aria-expanded');
  const files=()=>Array.from(host.querySelectorAll<HTMLElement>('[data-project-note-file-path]')).map(entry=>entry.dataset.projectNoteFilePath);
  expect(aria()).toBe('false');
  expect(files()).toEqual([]);
  expect(host.querySelector('[data-project-note-directory-path="Projects/Notes/Research/Nested"]')).toBeNull();
  h.click(rootKey);
  expect(toggles).toEqual(['Projects/Notes/Research']);
  expect(aria()).toBe('true');
  expect(files()).toEqual(['Projects/Notes/Research/root.md','Projects/Notes/Research/sketch.excalidraw']);
  expect(host.querySelector<HTMLElement>('[data-c1-key="'+nestedKey+'"]')?.getAttribute('aria-expanded')).toBe('false');
  expect(host.querySelector('[data-project-note-file-path="Projects/Notes/Research/Nested/child.md"]')).toBeNull();
  h.click(nestedKey);
  expect(toggles).toEqual(['Projects/Notes/Research','Projects/Notes/Research/Nested']);
  expect(host.querySelector<HTMLElement>('[data-c1-key="'+nestedKey+'"]')?.getAttribute('aria-expanded')).toBe('true');
  expect(files()).toEqual(['Projects/Notes/Research/Nested/board.canvas','Projects/Notes/Research/Nested/child.md','Projects/Notes/Research/root.md','Projects/Notes/Research/sketch.excalidraw']);
  h.click(rootKey);
  expect(toggles).toEqual(['Projects/Notes/Research','Projects/Notes/Research/Nested','Projects/Notes/Research']);
  expect(aria()).toBe('false');
  expect(files()).toEqual([]);
  expect(view.selectedPath).toBeNull();
 });
 it('offers the hover affordance on interactive entries only and keeps hover out of the handlers',async()=>{
  const linked=[{name:'Research',path:'Projects/Notes/Research'},{name:'Missing',path:'Projects/Notes/Missing'}];
  const linkedProject={...project,linkedFolders:linked};
  const tree=await loadProjectNotesTree(notesVault(),linkedProject);
  const view:ProjectNotesViewState={...ready(tree),expandedPaths:['Projects/Notes/Research']};
  const host=document.createElement('div');document.body.append(host);host.innerHTML=renderProjectNotes(linkedProject,view);
  expect(readFileSync(resolve(process.cwd(),'public/index.html'),'utf8')).toContain('.project-note-entry:hover');
  const entries=Array.from(host.querySelectorAll<HTMLElement>('[data-project-note-entry-path]'));
  expect(entries).toHaveLength(4);
  expect(entries.every(entry=>entry.classList.contains('project-note-entry'))).toBe(true);
  expect(entries.every(entry=>entry.tagName==='BUTTON')).toBe(true);
  const draggable=Array.from(host.querySelectorAll<HTMLElement>('[data-project-note-file-path]'));
  expect(draggable).toHaveLength(2);
  expect(draggable.every(file=>file.getAttribute('draggable')==='true')).toBe(true);
  expect(host.querySelector('[data-project-note-directory-path][draggable="true"]')).toBeNull();
  const unavailable=host.querySelector<HTMLElement>('[data-project-note-root-status="missing"]');
  expect(unavailable?.querySelector('[data-project-note-entry-path]')).toBeNull();
  expect(unavailable?.querySelector('.project-note-entry')).toBeNull();
  let calls=0;
  const counted=()=>{calls+=1;};
  bindProjectNotesInteractions(host,{toggleFolder:counted,selectFile:counted,openContext:counted,closeContext:counted,startDrag:counted,previewDrag:counted,refuseDrop:counted,clearDrag:counted});
  const h=createInteractionHarness(host);
  h.hover('project-note-root-'+project.id+'-Projects/Notes/Research');
  h.hover('project-note-file-'+project.id+'-Projects/Notes/Research/root.md');
  expect(calls).toBe(0);
  expect(view.selectedPath).toBeNull();
 });
 it('previews folder destinations only while dragging and clears the preview on drop',async()=>{
  const tree=await loadProjectNotesTree(notesVault(),project);
  let view:ProjectNotesViewState=ready(tree);
  const previews:string[][]=[];
  const host=document.createElement('div');document.body.append(host);const render=()=>{host.innerHTML=renderProjectNotes(project,view);};
  render();
  bindProjectNotesInteractions(host,{toggleFolder:()=>{},selectFile:()=>{},openContext:()=>{},closeContext:()=>{},startDrag:path=>{view={...view,dragSourcePath:path};},previewDrag:(source,target)=>{previews.push([source,target]);},refuseDrop:()=>{},clearDrag:()=>{}});
  const h=createInteractionHarness(host);
  const source='Projects/Notes/Research/root.md';
  const panel=()=>host.querySelector<HTMLElement>('[data-project-workspace-panel="notes"]');
  const drag=h.beginDrag('project-note-file-'+project.id+'-'+source,{clientX:0,clientY:0});
  expect(view.dragSourcePath).toBe(source);
  drag.move('project-note-file-'+project.id+'-Projects/Notes/Research/sketch.excalidraw',{clientX:1,clientY:1});
  expect(previews).toEqual([]);
  expect(panel()?.dataset.projectNoteDragPreview).toBeUndefined();
  drag.move('project-note-folder-'+project.id+'-Projects/Notes/Research/Nested',{clientX:2,clientY:2});
  expect(previews).toEqual([[source,'Projects/Notes/Research/Nested']]);
  expect(panel()?.dataset.projectNoteDragPreview).toBe(source+' -> Projects/Notes/Research/Nested');
  expect(panel()?.dataset.projectNoteDragTarget).toBe('Projects/Notes/Research/Nested');
  drag.drop('project-note-folder-'+project.id+'-Projects/Notes/Research/Nested',{clientX:2,clientY:2});
  expect(panel()?.dataset.projectNoteDragPreview).toBeUndefined();
 });
 it('inspects ordinary vault files as files, never as database records',async()=>{
  const files:Record<string,string>={'Projects/Notes/Research/plain.md':'# Plain','Projects/Notes/Research/record-like.md':'---\nid: task-notes-project\nstatus: todo\nweight: 3\n---\nNot a task record.','Projects/Notes/Research/data.json':'{"id":"task-notes-project"}','Projects/Notes/Research/Deep/More/leaf.md':'# Leaf'};
  const vault=createMemoryVault(files);
  const refuse=()=>{throw new Error('the notes read side attempted a write');};
  const guarded={...vault,writeIfUnchanged:refuse,createIfAbsent:refuse,moveIfUnchanged:refuse,deleteIfUnchanged:refuse,set:refuse,delete:refuse};
  const tree=await loadProjectNotesTree(guarded,project);
  expect(Object.keys(tree)).toEqual(['projectId','roots','fileCount']);
  expect(tree.fileCount).toBe(4);
  const root=tree.roots[0]!;
  expect(root.entries.filter(entry=>entry.kind==='directory').map(entry=>entry.path)).toEqual(['Projects/Notes/Research/Deep','Projects/Notes/Research/Deep/More']);
  expect(root.entries.filter(entry=>entry.kind==='file').map(entry=>entry.path)).toEqual(['Projects/Notes/Research/data.json','Projects/Notes/Research/Deep/More/leaf.md','Projects/Notes/Research/plain.md','Projects/Notes/Research/record-like.md']);
  const recordLike=await loadProjectNotePreview(guarded,'Projects/Notes/Research/record-like.md');
  expect(recordLike.failure).toBeNull();
  expect(recordLike.preview?.kind).toBe('markdown');
  if(recordLike.preview?.kind==='markdown')expect(recordLike.preview.text).toBe(files['Projects/Notes/Research/record-like.md']);
  expect(recordLike.preview?.revision).toBe('Projects/Notes/Research/record-like.md@1');
  const json=await loadProjectNotePreview(guarded,'Projects/Notes/Research/data.json');
  expect(json.preview).toBeNull();
  expect(json.failure).toBe('unsupported-format');
  for(const [path,text] of Object.entries(files))expect((await vault.read(path)).text).toBe(text);
 });
 it('states a failed preview and its reason instead of an empty pane',async()=>{
  const tree=await loadProjectNotesTree(notesVault(),project);
  const host=document.createElement('div');document.body.append(host);
  const base:ProjectNotesViewState=ready(tree);
  const render=(next:ProjectNotesViewState)=>{host.innerHTML=renderProjectNotes(project,next);};
  render({...base,previewStatus:'idle'});
  expect(host.querySelector('[data-project-note-preview-status="idle"]')?.textContent).toBe('Select a file to preview it.');
  render({...base,previewStatus:'loading'});
  expect(host.querySelector('[data-project-note-preview-status="loading"]')?.textContent).toContain('Loading preview');
  render({...base,previewStatus:'unavailable',previewFailure:'canvas-invalid'});
  expect(host.querySelector('[data-project-note-preview-status="unavailable"]')?.textContent).toContain('canvas-invalid');
  const preview=await loadProjectNotePreview(notesVault(),'Projects/Notes/Research/root.md');
  expect(preview.failure).toBeNull();
  render({...base,previewStatus:'ready',preview:preview.preview});
  expect(host.querySelector('[data-project-note-preview-kind="markdown"]')?.textContent).toBe('# Root');
 });
});
