import { describe, expect, it } from 'vitest';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import { createVaultMutationCoordinator } from '../src/app/vaultMutation.js';
import { loadVaultState } from '../src/app/vaultRepository.js';
import { promoteProjectLinkedFolders } from '../src/app/projectLinkedFoldersPromotion.js';
function readerFor(vault: ReturnType<typeof createMemoryVault>) { return { ...vault, readBinary: async (path: string, maxBytes: number) => { const file = await vault.read(path); return { ...file, bytes: new TextEncoder().encode(file.text) }; } }; }
function project(path: string, revision: string) { return { id: path.includes('folder') ? 'folder' : path.split('/').pop()!.replace(/\.md$/i, ''), source: { path, revision, kind: 'project' as const, idOrigin: 'filename' as const } }; }
describe('13.2S legacy linked-folder promotion', () => {
  it('promotes singular and packed legacy forms with identical reload semantics', async () => { const vault = createMemoryVault({ 'Proxima/projects/singular.md': '---\nid: singular\nlinkedFolder: Notes\n---\nbody', 'Proxima/projects/folder/index.md': '---\nid: folder\nlinkedFolders: Art|Drawings/Art;Refs\n---\nbody' }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let f = await reader.read('Proxima/projects/singular.md'); expect(await promoteProjectLinkedFolders({ project: project(f.path, f.revision), reader, coordinator })).toMatchObject({ ok: true }); f = await reader.read('Proxima/projects/folder/index.md'); expect(await promoteProjectLinkedFolders({ project: project(f.path, f.revision), reader, coordinator })).toMatchObject({ ok: true }); expect((await loadVaultState(reader)).state.projects.find((p) => p.id === 'singular')?.linkedFolders).toMatchObject([{ path: 'Notes' }]); expect((await loadVaultState(reader)).state.projects.find((p) => p.id === 'folder')?.linkedFolders).toMatchObject([{ name: 'Art', path: 'Drawings/Art' }, { path: 'Refs' }]); });
  it('preferred/no-source are no-ops and ambiguous or malformed legacy forms refuse', async () => { const vault = createMemoryVault({ 'Proxima/projects/p.md': '---\nid: p\nlinkedFolders: ["Notes"]\n---\nbody', 'Proxima/projects/mixed.md': '---\nlinkedFolder: Notes\nlinkedFolders: Other\n---\nbody', 'Proxima/projects/bad.md': '---\nlinkedFolders: A|;B|Other\n---\nbody' }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); for (const path of ['Proxima/projects/p.md', 'Proxima/projects/none.md']) { if (path.endsWith('none.md')) continue; const f = await reader.read(path); expect(await promoteProjectLinkedFolders({ project: project(f.path, f.revision), reader, coordinator })).toMatchObject({ ok: true, noOp: true }); } let f = await reader.read('Proxima/projects/mixed.md'); expect(await promoteProjectLinkedFolders({ project: project(f.path, f.revision), reader, coordinator })).toMatchObject({ ok: false }); f = await reader.read('Proxima/projects/bad.md'); expect(await promoteProjectLinkedFolders({ project: project(f.path, f.revision), reader, coordinator })).toMatchObject({ ok: false }); });
  it('refuses duplicate semantic paths and stale peers', async () => { const vault = createMemoryVault({ 'Proxima/projects/dup.md': '---\nlinkedFolders: A|Same;B|Same\n---\nbody', 'Proxima/projects/stale.md': '---\nlinkedFolder: Notes\n---\nbody' }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let f = await reader.read('Proxima/projects/dup.md'); expect(await promoteProjectLinkedFolders({ project: project(f.path, f.revision), reader, coordinator })).toMatchObject({ ok: false, reason: 'target-ambiguous' }); f = await reader.read('Proxima/projects/stale.md'); vault.set(f.path, '---\nlinkedFolder: Peer\n---\npeer'); expect(await promoteProjectLinkedFolders({ project: project(f.path, f.revision), reader, coordinator })).toMatchObject({ ok: false, reason: 'stale' }); expect((await vault.read(f.path)).text).toContain('linkedFolder: Peer'); });
});
