// @vitest-environment happy-dom
import { beforeEach, describe, expect, it } from 'vitest';
import { loadProjectNotePreview, loadProjectNotesTree } from '../src/app/projectNotes.js';
import { bindProjectNotesInteractions, EMPTY_PROJECT_NOTES_VIEW, PROJECT_NOTE_WRITE_REFUSAL, renderProjectNotes, type ProjectNotesViewState } from '../src/browser/projectNotes.js';
import { createInteractionHarness } from '../src/browser/interactionHarness.js';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import type { Project } from '../src/domain/types.js';
import { sourceRef } from './fixtures.js';
const project:Project={id:'notes-project',source:sourceRef('project','notes-project'),name:'Notes Project',description:'Detailed linked notes',createdAt:'2026-09-01T00:00:00.000Z',status:'active',projectType:'task',linkedFolders:[{name:'Research',path:'Projects/Notes/Research'}]};
const notesVault=()=>createMemoryVault({'Projects/Notes/Research/root.md':'# Root','Projects/Notes/Research/Nested/child.md':'# Child','Projects/Notes/Research/Nested/board.canvas':JSON.stringify({nodes:[{id:'n1',type:'text',text:'Alpha'},{id:'n2',type:'file',file:'Beta.md'}],edges:[{id:'e1',fromNode:'n1',toNode:'n2'}]}),'Projects/Notes/Research/sketch.excalidraw':JSON.stringify({type:'excalidraw',version:2,elements:[],appState:{},files:{}}),'Outside/secret.md':'# Secret'});
const ready=(tree:Awaited<ReturnType<typeof loadProjectNotesTree>>):ProjectNotesViewState=>({...EMPTY_PROJECT_NOTES_VIEW,projectId:project.id,sourceGeneration:1,treeStatus:'ready',tree,expandedPaths:['Projects/Notes/Research']});
beforeEach(()=>{document.body.innerHTML='';});
describe('Stage 5 slice 5 detailed Notes tree and preview interactions',()=>{
 it('builds a deterministic recursive tree only beneath linked roots',async()=>{const t=await loadProjectNotesTree(notesVault(),project);expect(t.fileCount).toBe(4);expect(t.roots[0]?.entries.map(e=>[e.kind,e.path])).toEqual([['directory','Projects/Notes/Research/Nested'],['file','Projects/Notes/Research/Nested/board.canvas'],['file','Projects/Notes/Research/Nested/child.md'],['file','Projects/Notes/Research/root.md'],['file','Projects/Notes/Research/sketch.excalidraw']]);expect(t.roots[0]?.entries.some(e=>e.path.includes('Outside'))).toBe(false);});
 it('previews Markdown, Canvas and Excalidraw',async()=>{const r=notesVault();const m=await loadProjectNotePreview(r,'Projects/Notes/Research/root.md');expect(m.preview?.kind).toBe('markdown');const c=await loadProjectNotePreview(r,'Projects/Notes/Research/Nested/board.canvas');expect(c.preview?.kind).toBe('canvas');if(c.preview?.kind==='canvas'){expect(c.preview.nodeCount).toBe(2);expect(c.preview.edgeCount).toBe(1);}const e=await loadProjectNotePreview(r,'Projects/Notes/Research/sketch.excalidraw');expect(e.preview?.kind).toBe('excalidraw');});
 it('fails closed for unsafe roots and unsupported previews',async()=>{const t=await loadProjectNotesTree(notesVault(),{...project,linkedFolders:[{name:'Unsafe',path:'../Outside'},{name:'Missing',path:'Projects/Notes/Missing'}]});expect(t.roots.map(r=>r.status)).toEqual(['unavailable','missing']);expect((await loadProjectNotePreview(notesVault(),'../Outside/secret.md')).failure).toBe('invalid-path');expect((await loadProjectNotePreview(createMemoryVault({'Projects/Notes/Research/file.txt':'x'}),'Projects/Notes/Research/file.txt')).failure).toBe('unsupported-format');});
 it('keeps local selection/context and write controls unavailable',async()=>{const tree=await loadProjectNotesTree(notesVault(),project);let view=ready(tree);const render=()=>{document.body.innerHTML=renderProjectNotes(project,view);};render();bindProjectNotesInteractions(document.body,{toggleFolder:()=>{},selectFile:p=>{view={...view,selectedPath:p};render();},openContext:p=>{view={...view,contextPath:p};render();},closeContext:()=>{view={...view,contextPath:null};render();},startDrag:()=>{},previewDrag:()=>{},refuseDrop:()=>{},clearDrag:()=>{}});const h=createInteractionHarness(document);const p='Projects/Notes/Research/root.md';h.click('project-note-file-'+project.id+'-'+p);expect(view.selectedPath).toBe(p);h.contextMenu('project-note-file-'+project.id+'-'+p);const controls=Array.from(document.querySelectorAll<HTMLButtonElement>('[data-project-note-write-action]'));expect(controls).toHaveLength(3);expect(controls.every(c=>c.disabled&&c.dataset.projectNoteWriteRefusal===PROJECT_NOTE_WRITE_REFUSAL)).toBe(true);h.escape('project-note-file-'+project.id+'-'+p);expect(view.contextPath).toBeNull();});
 it('previews drag destination and refuses drop',async()=>{const tree=await loadProjectNotesTree(notesVault(),project);let view=ready(tree);let refused:null|{sourcePath:string;targetPath:string}=null;const render=()=>{document.body.innerHTML=renderProjectNotes(project,view);};render();bindProjectNotesInteractions(document.body,{toggleFolder:()=>{},selectFile:()=>{},openContext:()=>{},closeContext:()=>{},startDrag:p=>{view={...view,dragSourcePath:p};},previewDrag:(s,t)=>{view={...view,dragSourcePath:s,dragTargetPath:t};},refuseDrop:(s,t)=>{refused={sourcePath:s,targetPath:t};view={...view,writeRefusal:PROJECT_NOTE_WRITE_REFUSAL,lastRefusedMove:{sourcePath:s,targetPath:t}};render();},clearDrag:()=>{}});const h=createInteractionHarness(document);const s='Projects/Notes/Research/root.md',t='Projects/Notes/Research/Nested';const d=h.beginDrag('project-note-file-'+project.id+'-'+s,{clientX:0,clientY:0});d.move('project-note-folder-'+project.id+'-'+t,{clientX:1,clientY:1});expect(document.querySelector<HTMLElement>('[data-project-workspace-panel=\"notes\"]')?.dataset.projectNoteDragPreview).toBe(s+' -> '+t);d.drop('project-note-folder-'+project.id+'-'+t,{clientX:1,clientY:1});expect(refused).toEqual({sourcePath:s,targetPath:t});});
});
