// @vitest-environment happy-dom
import { beforeEach, describe, expect, it } from 'vitest';
import { bindProjectScheduleInteractions, EMPTY_PROJECT_SCHEDULE_VIEW, PROJECT_SCHEDULE_WRITE_REFUSAL, renderProjectSchedule, type ProjectScheduleViewState } from '../src/browser/projectSchedule.js';
import { createInteractionHarness } from '../src/browser/interactionHarness.js';
import type { CalendarEvent, Project, ProximaState } from '../src/domain/types.js';
import { sourceRef } from './fixtures.js';
const now=new Date('2026-09-06T12:00:00.000Z');const project:Project={id:'schedule-project',source:sourceRef('project','schedule-project'),name:'Schedule',description:'',createdAt:'2026-09-01T00:00:00.000Z',status:'active',projectType:'schedule',linkedFolders:[]};const other={...project,id:'other-project',source:sourceRef('project','other-project')};const event=(id:string,pid:string,start:string,done=false):CalendarEvent=>({id,source:sourceRef('event',id),name:id,description:'<script>not executable</script>',projectId:pid,createdAt:'2026-09-01T00:00:00.000Z',startDate:start,deadline:start,isCompleted:done,properties:{location:'<b>Room</b>'}});const state=():ProximaState=>({projects:[project,other],tasks:[],events:[event('upcoming',project.id,'2026-09-08T09:00:00.000Z'),event('completed',project.id,'2026-09-05T09:00:00.000Z',true),event('past',project.id,'2026-09-04T09:00:00.000Z'),event('invalid',project.id,'not-a-date'),event('foreign',other.id,'2026-09-03T09:00:00.000Z')],statuses:[],taskSchema:[]});beforeEach(()=>{document.body.innerHTML='';});
describe('Stage 5 slice 9 detailed Schedule interactions',()=>{
 it('scopes and orders events',()=>{const s=state();document.body.innerHTML=renderProjectSchedule(s,project,now);expect(Array.from(document.querySelectorAll('[data-project-schedule-event-id]')).map(x=>(x as HTMLElement).dataset.projectScheduleEventId)).toEqual(['past','completed','upcoming','invalid']);expect(document.querySelector('[data-project-schedule-event-id="foreign"]')).toBeNull();});
 it('filters locally',()=>{const s=state();let v:ProjectScheduleViewState={...EMPTY_PROJECT_SCHEDULE_VIEW,projectId:project.id};const r=()=>{document.body.innerHTML=renderProjectSchedule(s,project,now,v);};r();bindProjectScheduleInteractions(document.body,{setFilter:f=>{v={...v,filter:f};r();},openEvent:()=>{},closeEvent:()=>{}});const h=createInteractionHarness(document);h.click('project-schedule-filter-upcoming');expect(document.querySelectorAll('[data-project-schedule-event-id]')).toHaveLength(1);});
 it('opens escaped read-only inspector',()=>{const s=state();let v:ProjectScheduleViewState={...EMPTY_PROJECT_SCHEDULE_VIEW,projectId:project.id};const r=()=>{document.body.innerHTML=renderProjectSchedule(s,project,now,v);};r();bindProjectScheduleInteractions(document.body,{setFilter:()=>{},openEvent:id=>{v={...v,selectedEventId:id};r();},closeEvent:()=>{v={...v,selectedEventId:null};r();}});createInteractionHarness(document).click('project-schedule-event-upcoming');expect(document.querySelector('[data-project-schedule-inspector-event-id="upcoming"]')).not.toBeNull();expect(document.querySelector('.project-schedule-event-inspector script')).toBeNull();expect(document.querySelectorAll('[data-project-schedule-write-action]')).toHaveLength(3);});
 it('does not leak foreign view',()=>{const v:ProjectScheduleViewState={projectId:other.id,filter:'past',selectedEventId:'foreign'};document.body.innerHTML=renderProjectSchedule(state(),project,now,v);expect(document.querySelector('[data-project-schedule-inspector-event-id]')).toBeNull();expect(document.querySelector('[data-project-schedule-event-id="foreign"]')).toBeNull();});
});
