import { describe, expect, it } from 'vitest';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import { createVaultMutationCoordinator } from '../src/app/vaultMutation.js';
import { createProject } from '../src/app/projectCreation.js';
import { loadVaultState } from '../src/app/vaultRepository.js';
function coordinator(vault: ReturnType<typeof createMemoryVault>) { return createVaultMutationCoordinator({ reader: vault, writer: vault }); }
describe('13.2Q canonical project creation', () => {
  it('creates a flat project and reloads supplied metadata', async () => { const vault = createMemoryVault({}); const result = await createProject({ coordinator: coordinator(vault), input: { id: '01', name: 'Project', createdAt: '2026-09-08', status: 'archived', projectType: 'schedule', tabBgColor: '#abc', tabTextColor: 'white', description: 'Explicit', body: 'body' } }); expect(result).toMatchObject({ ok: true, path: 'Proxima/projects/01.md' }); expect((await loadVaultState(vault)).state.projects[0]).toMatchObject({ id: '01', name: 'Project', status: 'archived', projectType: 'schedule', tabBgColor: '#abc', tabTextColor: 'white', description: 'Explicit', source: { idOrigin: 'frontmatter', path: 'Proxima/projects/01.md' } }); });
  it('quotes YAML-sensitive strings and leaves absent description as body fallback', async () => { const vault = createMemoryVault({}); expect(await createProject({ coordinator: coordinator(vault), input: { id: 'null', name: 'null', createdAt: '2026-09-08', body: 'body fallback' } })).toMatchObject({ ok: true }); const text = (await vault.read('Proxima/projects/null.md')).text; expect(text).toContain('id: "null"'); expect(text).toContain('name: "null"'); expect((await loadVaultState(vault)).state.projects[0]).toMatchObject({ id: 'null', description: 'body fallback', status: 'active', projectType: 'task' }); });
  it('validates before coordinator and uses exclusive create', async () => { const vault = createMemoryVault({}); let calls = 0; const base = coordinator(vault); const spy = { execute: async (...args: Parameters<typeof base.execute>) => { calls += 1; return base.execute(...args); } }; expect(await createProject({ coordinator: spy, input: { id: '../x', name: 'x', createdAt: '2026-09-08' } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(await createProject({ coordinator: spy, input: { id: 'CON.txt', name: 'x', createdAt: '2026-09-08' } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(await createProject({ coordinator: spy, input: { id: 'x', name: 'x', createdAt: 'bad' } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(calls).toBe(0); const existing = createMemoryVault({ 'Proxima/projects/x.md': 'creator' }); expect(await createProject({ coordinator: coordinator(existing), input: { id: 'x', name: 'mine', createdAt: '2026-09-08' } })).toMatchObject({ ok: false, reason: 'already-exists' }); });
});
