// @vitest-environment happy-dom
import { beforeEach, describe, expect, it } from 'vitest';
import { bindProjectBacklogInteractions, EMPTY_PROJECT_BACKLOG_VIEW, PROJECT_BACKLOG_WRITE_REFUSAL, renderProjectBacklog, type ProjectBacklogViewState } from '../src/browser/projectBacklog.js';
import { createInteractionHarness } from '../src/browser/interactionHarness.js';
import type { Project, ProximaState, Task } from '../src/domain/types.js';
import { sourceRef } from './fixtures.js';
const project:Project={id:'backlog-project',source:sourceRef('project','backlog-project'),name:'Backlog',description:'',createdAt:'2026-09-01T00:00:00.000Z',status:'active',projectType:'task',linkedFolders:[]};
const other:Project={...project,id:'other',source:sourceRef('project','other'),name:'Other'};
const task=(id:string,pid:string,ix:number):Task=>({id,source:sourceRef('task',id),name:id,description:'<script>x</script>',projectId:pid,status:'todo',weight:1,orderIndex:ix,isFixedDuration:false,fixedDuration:null,maxDuration:null,isCompleted:false,createdAt:'2026-09-01T00:00:00.000Z',startDate:null,deadline:null,properties:{}});
const state=():ProximaState=>({projects:[project,other],tasks:[task('second',project.id,2),task('first',project.id,1),task('other',other.id,0)],events:[],statuses:[],taskSchema:[]});
beforeEach(()=>{document.body.innerHTML='';});
describe('Stage 5 slice 7 detailed Backlog interactions',()=>{
 it('orders and scopes tasks without mutation',()=>{const s=state(),before=JSON.stringify(s);document.body.innerHTML=renderProjectBacklog(s,project);expect(Array.from(document.querySelectorAll('[data-project-backlog-task-id]')).map(x=>(x as HTMLElement).dataset.projectBacklogTaskId)).toEqual(['first','second']);expect(document.querySelector('[data-project-backlog-task-id="other"]')).toBeNull();expect(JSON.stringify(s)).toBe(before);});
 it('opens a read-only inspector',()=>{const s=state();let v:ProjectBacklogViewState=EMPTY_PROJECT_BACKLOG_VIEW;const r=()=>{document.body.innerHTML=renderProjectBacklog(s,project,v);};r();bindProjectBacklogInteractions(document.body,{openTask:id=>{v={...v,projectId:project.id,selectedTaskId:id};r();},closeTask:()=>{v={...v,selectedTaskId:null};r();},startDrag:()=>{},previewMove:()=>{},refuseMove:()=>{},clearDrag:()=>{}});createInteractionHarness(document).click('project-backlog-task-first');expect(document.querySelector('[data-project-backlog-inspector-task-id="first"]')).not.toBeNull();expect(document.querySelector('.project-backlog-task-inspector script')).toBeNull();});
 it('refuses provisional reorder drops',()=>{const s=state();let v:ProjectBacklogViewState={...EMPTY_PROJECT_BACKLOG_VIEW,projectId:project.id};let refused:any=null;const r=()=>{document.body.innerHTML=renderProjectBacklog(s,project,v);};r();bindProjectBacklogInteractions(document.body,{openTask:()=>{},closeTask:()=>{},startDrag:id=>{v={...v,dragTaskId:id};},previewMove:()=>{},refuseMove:i=>{refused=i;v={...v,writeRefusal:PROJECT_BACKLOG_WRITE_REFUSAL};r();},clearDrag:()=>{}});const h=createInteractionHarness(document),d=h.beginDrag('project-backlog-task-first',{clientX:0,clientY:0});d.move('project-backlog-drop-'+project.id+'-1',{clientX:1,clientY:1});expect(document.querySelector('[data-project-backlog-drop-index="1"] .project-backlog-insertion-placeholder')?.getAttribute('style')).toContain('height');d.drop('project-backlog-drop-'+project.id+'-1',{clientX:1,clientY:1});expect(refused).toEqual({taskId:'first',targetIndex:1});});
 it('does not leak foreign view state',()=>{const v:ProjectBacklogViewState={...EMPTY_PROJECT_BACKLOG_VIEW,projectId:other.id,selectedTaskId:'other',writeRefusal:PROJECT_BACKLOG_WRITE_REFUSAL,lastRefusedMove:{taskId:'other',targetIndex:0}};document.body.innerHTML=renderProjectBacklog(state(),project,v);expect(document.querySelector('[data-project-backlog-inspector-task-id]')).toBeNull();expect(document.querySelector('[data-project-backlog-write-refusal]')).toBeNull();});
});
