// @vitest-environment happy-dom
import { beforeEach, describe, expect, it } from 'vitest';
import { bindProjectsHubInteractions, projectsHubCards, renderProjectsHub, type ProjectsHubFilter } from '../src/browser/projectsHub.js';
import { createInteractionHarness } from '../src/browser/interactionHarness.js';
import type { Project, ProximaState, Task } from '../src/domain/types.js';
import { sourceRef } from './fixtures.js';

const NOW = new Date('2026-09-10T12:00:00.000Z');
function project(id:string,status:'active'|'archived',createdAt:string,colors:{background?:string;text?:string}={}):Project { return { id, source:sourceRef('project',id), name:id==='project-active'?'Active Project':'Archived Project', description:`${status} project description`, createdAt, status, projectType:'task', archivedAt:status==='archived'?'2026-09-02T00:00:00.000Z':undefined, tabBgColor:colors.background, tabTextColor:colors.text, linkedFolders:[] }; }
function task(id:string,projectId:string,deadline:string|null,options:{completed?:boolean;priority?:unknown}={}):Task { return { id, source:sourceRef('task',id), name:id, description:'', projectId, status:options.completed?'done':'todo', weight:1, orderIndex:0, isFixedDuration:false, fixedDuration:null, maxDuration:null, isCompleted:options.completed??false, createdAt:'2026-09-01T00:00:00.000Z', startDate:null, deadline, properties:options.priority===undefined?{}:{priority:options.priority} }; }
function stateFixture():ProximaState { return { projects:[project('project-active','active','2026-09-01T00:00:00.000Z',{background:'#112233',text:'#ffffff'}),project('project-archived','archived','2026-08-01T00:00:00.000Z')],tasks:[task('task-overdue-p1','project-active','2026-09-05T09:00:00.000Z',{priority:'priority-p1'}),task('task-upcoming','project-active','2026-09-12T09:00:00.000Z',{priority:'medium'}),task('task-completed-old','project-active','2026-09-02T09:00:00.000Z',{completed:true,priority:'priority-p1'}),task('task-archived-project','project-archived',null)],events:[],statuses:[],taskSchema:[{id:'priority',name:'Priority',type:'select',options:[{id:'priority-p1',name:'P1',color:'#ff0000'},{id:'medium',name:'Medium',color:'#cccccc'}]}]}; }
beforeEach(()=>{document.body.innerHTML='';});
describe('Stage 5 Projects Hub read-only inventory',()=>{
  it('derives deterministic card facts without changing project or task records',()=>{const state=stateFixture();const before=JSON.stringify(state);expect(projectsHubCards(state,'active',NOW)).toEqual([{id:'project-active',name:'Active Project',description:'active project description',status:'active',ageDays:9,taskCount:3,overdueCount:1,highPriorityCount:1,nextDeadline:'2026-09-12T09:00:00.000Z',identityBackground:'#112233',identityText:'#ffffff'}]);expect(projectsHubCards(state,'archived',NOW)).toEqual([{id:'project-archived',name:'Archived Project',description:'archived project description',status:'archived',ageDays:40,taskCount:1,overdueCount:0,highPriorityCount:0,nextDeadline:null,identityBackground:null,identityText:null}]);expect(JSON.stringify(state)).toBe(before);});
  it('renders every required card fact and visual identity without assuming legacy projectType presentation',()=>{const state=stateFixture();document.body.innerHTML=renderProjectsHub({state,selection:'all',filter:'active',workspaceTab:'notes',now:NOW});const harness=createInteractionHarness(document);const card=harness.target('project-hub-card-project-active');expect(card.dataset.projectArchiveState).toBe('active');expect(card.dataset.projectAgeDays).toBe('9');expect(card.dataset.projectTaskCount).toBe('3');expect(card.dataset.projectOverdueCount).toBe('1');expect(card.dataset.projectNextDeadline).toBe('2026-09-12T09:00:00.000Z');expect(card.querySelector<HTMLElement>('[data-project-high-priority-count]')?.dataset.projectHighPriorityCount).toBe('1');const swatch=card.querySelector<HTMLElement>('[data-project-identity-bg]');expect(swatch?.dataset.projectIdentityBg).toBe('#112233');expect(swatch?.dataset.projectIdentityText).toBe('#ffffff');expect(swatch?.getAttribute('style')).toContain('background-color:#112233');expect(card.textContent).toContain('Active Project');expect(card.textContent).toContain('active project description');expect(card.textContent).toContain('9d');expect(card.textContent).toContain('2026-09-12T09:00:00.000Z');expect(card.textContent).not.toContain('Task project');expect(()=>harness.target('project-hub-card-project-archived')).toThrow();});
  it('filters active and archived cards and opens or leaves a workspace through programmatic clicks without mutating source state',()=>{const state=stateFixture();const before=JSON.stringify(state);document.body.innerHTML='<div id="root"></div>';const root=document.querySelector<HTMLElement>('#root')!;let filter:ProjectsHubFilter='active';let selection='all';const rerender=()=>{root.innerHTML=renderProjectsHub({state,selection,filter,workspaceTab:'notes',now:NOW});};bindProjectsHubInteractions(root,{setFilter:(next)=>{filter=next;rerender();},openProject:(projectId)=>{selection=projectId;rerender();},showHub:()=>{selection='all';rerender();}});rerender();const harness=createInteractionHarness(root);expect(root.querySelector<HTMLElement>('[data-projects-hub-filter]')?.dataset.projectsHubFilter).toBe('active');harness.click('project-hub-filter-archived');expect(filter).toBe('archived');expect(harness.target('project-hub-card-project-archived')).toBeInstanceOf(HTMLElement);expect(()=>harness.target('project-hub-card-project-active')).toThrow();harness.click('project-hub-card-project-archived');expect(selection).toBe('project-archived');expect(root.querySelector<HTMLElement>('[data-project-workspace-project-id]')?.dataset.projectWorkspaceProjectId).toBe('project-archived');expect(harness.target('project-workspace-notes')).toBeInstanceOf(HTMLElement);harness.click('project-hub-back');expect(selection).toBe('all');expect(root.querySelector<HTMLElement>('[data-projects-hub-filter]')?.dataset.projectsHubFilter).toBe('archived');expect(JSON.stringify(state)).toBe(before);});
});
