import { describe, expect, it } from 'vitest';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import { createVaultMutationCoordinator } from '../src/app/vaultMutation.js';
import { renameProjectSource, deleteProjectSource } from '../src/app/projectSourceLifecycle.js';
import { renameEventSource, deleteEventSource } from '../src/app/eventSourceLifecycle.js';
describe('project and event lifecycle',()=>{
 it('renames/deletes flat and folder projects with identity boundaries',async()=>{const v=createMemoryVault({'Proxima/projects/p.md':'p','Proxima/projects/folder/index.md':'f'});const c=createVaultMutationCoordinator({reader:v,writer:v});let p=await v.read('Proxima/projects/p.md');expect(await renameProjectSource({project:{id:'p',source:{path:p.path,revision:p.revision,kind:'project',idOrigin:'frontmatter'}},newFileStem:'renamed',coordinator:c})).toMatchObject({ok:true});expect((await v.read('Proxima/projects/renamed.md')).text).toBe('p');let f=await v.read('Proxima/projects/folder/index.md');expect(await renameProjectSource({project:{id:'folder',source:{path:f.path,revision:f.revision,kind:'project',idOrigin:'frontmatter'}},newFileStem:'newfolder',coordinator:c})).toMatchObject({ok:true});expect((await v.read('Proxima/projects/newfolder/index.md')).text).toBe('f');const n=await v.read('Proxima/projects/renamed.md');expect(await deleteProjectSource({project:{id:'renamed',source:{path:n.path,revision:n.revision,kind:'project',idOrigin:'frontmatter'}},coordinator:c})).toMatchObject({ok:true});});
 it('renames/deletes events, refuses legacy rename and preserves collisions',async()=>{const v=createMemoryVault({'Proxima/events/e.md':'e','Proxima/events/x.md':'x'});const c=createVaultMutationCoordinator({reader:v,writer:v});let e=await v.read('Proxima/events/e.md');expect(await renameEventSource({event:{id:'e',source:{path:e.path,revision:e.revision,kind:'event',idOrigin:'frontmatter'}},newFileStem:'renamed',coordinator:c})).toMatchObject({ok:true});expect((await v.read('Proxima/events/renamed.md')).text).toBe('e');const r=await v.read('Proxima/events/renamed.md');expect(await deleteEventSource({event:{id:'renamed',source:{path:r.path,revision:r.revision,kind:'event',idOrigin:'frontmatter'}},coordinator:c})).toMatchObject({ok:true});const x=await v.read('Proxima/events/x.md');expect(await renameEventSource({event:{id:'x',source:{path:x.path,revision:x.revision,kind:'event',idOrigin:'filename'}},newFileStem:'z',coordinator:c})).toMatchObject({ok:false,reason:'rename-requires-explicit-id'});});
 it('rejects outside, nested, unsafe and stale lifecycle provenance',async()=>{const v=createMemoryVault({'Proxima/events/e.md':'e','Proxima/projects/folder/index.md':'f'});let calls=0;const base=createVaultMutationCoordinator({reader:v,writer:v});const c={execute:async(...args:Parameters<typeof base.execute>)=>{calls++;return base.execute(...args)}};const rev=(await v.read('Proxima/events/e.md')).revision;expect(await deleteEventSource({event:{id:'e',source:{path:'Notes/e.md',revision:rev,kind:'event',idOrigin:'frontmatter'}},coordinator:c})).toMatchObject({ok:false,reason:'invalid-provenance'});expect(await renameEventSource({event:{id:'e',source:{path:'Proxima/events/e.md',revision:rev,kind:'event',idOrigin:'frontmatter'}},newFileStem:'CON.txt',coordinator:c})).toMatchObject({ok:false,reason:'invalid-name'});const fp=await v.read('Proxima/projects/folder/index.md');expect(await renameProjectSource({project:{id:'folder',source:{path:fp.path,revision:fp.revision,kind:'project',idOrigin:'frontmatter'}},newFileStem:'folder.',coordinator:c})).toMatchObject({ok:false,reason:'invalid-name'});expect(await renameProjectSource({project:{id:'folder',source:{path:fp.path,revision:fp.revision,kind:'project',idOrigin:'frontmatter'}},newFileStem:'folder..',coordinator:c})).toMatchObject({ok:false,reason:'invalid-name'});expect(calls).toBe(0);v.set('Proxima/events/e.md','peer');expect(await deleteEventSource({event:{id:'e',source:{path:'Proxima/events/e.md',revision:rev,kind:'event',idOrigin:'frontmatter'}},coordinator:c})).toMatchObject({ok:false,reason:'stale'});});
});
