import { describe, expect, it } from 'vitest';
import { createMemoryVault } from '../src/adapters/memoryVault.js';
import { createVaultMutationCoordinator } from '../src/app/vaultMutation.js';
import { loadVaultState } from '../src/app/vaultRepository.js';
import { updateTaskDescription } from '../src/app/taskDescriptionMutation.js';

function readerFor(vault: ReturnType<typeof createMemoryVault>) { return { ...vault, readBinary: async (path: string, maxBytes: number) => { const file = await vault.read(path); const bytes = new TextEncoder().encode(file.text); if (bytes.byteLength > maxBytes) throw new Error('large'); return { ...file, bytes }; } }; }
function task(revision: string, path = 'Proxima/tasks/t1.md') { return { id: 't1', source: { path, revision, kind: 'task' as const, idOrigin: 'frontmatter' as const } }; }
const source = '\uFEFF---\r\nid: t1\r\nname: Task\r\nproject: p\r\nstatus: running\r\ndescription: Old # keep\r\nforeign: &x value\r\n---\r\nbody fallback\r\n';

describe('13.2O task description override/body fallback', () => {
  it('sets then uses body while preserving task fields and exact bytes', async () => { const vault = createMemoryVault({ 'Proxima/tasks/t1.md': source }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let observed = await reader.read('Proxima/tasks/t1.md'); expect(await updateTaskDescription({ task: task(observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'set', value: 'New task description' } })).toMatchObject({ ok: true }); observed = await reader.read(observed.path); expect((await loadVaultState(reader)).state.tasks.find((t) => t.id === 't1')).toMatchObject({ description: 'New task description', projectId: 'p', status: 'running' }); expect(await updateTaskDescription({ task: task(observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'use-body' } })).toMatchObject({ ok: true }); const text = (await reader.read(observed.path)).text; expect(text).not.toContain('description:'); expect(text).toContain('foreign: &x value\r\n---\r\nbody fallback\r\n'); expect((await loadVaultState(reader)).state.tasks.find((t) => t.id === 't1')).toMatchObject({ description: 'body fallback' }); });
  it('inserts missing description and absent use-body is a no-op', async () => { const vault = createMemoryVault({ 'Proxima/tasks/t1.md': '---\nid: t1\nname: Task\nstatus: running\n---\nbody' }); const reader = readerFor(vault); const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); let observed = await reader.read('Proxima/tasks/t1.md'); expect(await updateTaskDescription({ task: task(observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'set', value: 'Inserted' } })).toMatchObject({ ok: true }); observed = await reader.read(observed.path); expect((await loadVaultState(reader)).state.tasks.find((t) => t.id === 't1')).toMatchObject({ description: 'Inserted' }); expect(await updateTaskDescription({ task: task(observed.revision), path: observed.path, reader, coordinator, mutation: { kind: 'use-body' } })).toMatchObject({ ok: true }); });
  it('refuses invalid authority, block scalar and out-of-scope provenance before reads', async () => { const vault = createMemoryVault({ 'Proxima/tasks/t1.md': source }); let reads = 0; const base = readerFor(vault); const reader = { ...base, readBinary: async (path: string, maxBytes: number) => { reads += 1; return base.readBinary(path, maxBytes); } }; const coordinator = createVaultMutationCoordinator({ reader, writer: vault }); const rev = (await reader.read('Proxima/tasks/t1.md')).revision; const common = { task: task(rev), path: 'Proxima/tasks/t1.md', reader, coordinator }; expect(await updateTaskDescription({ ...common, mutation: { kind: 'clear' as never } })).toMatchObject({ ok: false, reason: 'field-not-allowed' }); expect(await updateTaskDescription({ ...common, mutation: { kind: 'set', value: '' } })).toMatchObject({ ok: false, reason: 'invalid-value' }); expect(await updateTaskDescription({ ...common, task: task(rev, 'Proxima/events/t1.md'), mutation: { kind: 'use-body' } })).toMatchObject({ ok: false, reason: 'invalid-provenance' }); expect(reads).toBe(0); vault.set('Proxima/tasks/t1.md', '---\nid: t1\ndescription: |\n  block\n---\nbody'); const blockRev = (await reader.read('Proxima/tasks/t1.md')).revision; expect(await updateTaskDescription({ ...common, task: task(blockRev), mutation: { kind: 'use-body' } })).toMatchObject({ ok: false, reason: 'target-unsupported' }); });
});
