import type { ActionErrorCode } from '../app/actionProtocol.js';
import type { CalendarEvent, Project, ProximaState } from '../domain/types.js';
export type ProjectScheduleFilter = 'all' | 'upcoming' | 'past' | 'completed' | 'invalid';
export type ProjectScheduleEventState = 'upcoming' | 'past' | 'completed' | 'invalid';
export type ProjectScheduleWriteRefusal = Extract<ActionErrorCode, 'action-not-available'>;
export const PROJECT_SCHEDULE_WRITE_REFUSAL: ProjectScheduleWriteRefusal = 'action-not-available';
export interface ProjectScheduleViewState { projectId: string | null; filter: ProjectScheduleFilter; selectedEventId: string | null; }
export const EMPTY_PROJECT_SCHEDULE_VIEW: ProjectScheduleViewState = { projectId: null, filter: 'all', selectedEventId: null };
export interface ProjectScheduleHandlers { setFilter(filter: ProjectScheduleFilter): void; openEvent(eventId: string): void; closeEvent(): void; }
const esc = (v: unknown) => String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&#39;");
function eventState(e: CalendarEvent, now: Date): ProjectScheduleEventState { const ms = Date.parse(e.startDate); return !Number.isFinite(ms) ? 'invalid' : e.isCompleted ? 'completed' : ms < now.getTime() ? 'past' : 'upcoming'; }
export function renderProjectSchedule(state: ProximaState, project: Project, now: Date, view: ProjectScheduleViewState = EMPTY_PROJECT_SCHEDULE_VIEW): string {
  const events = state.events.filter(e => e.projectId === project.id);
  const active = view.projectId === project.id, filter = active ? view.filter : 'all', selected = active ? view.selectedEventId : null;
  const ordered = events.slice().sort((a,b) => { const am=Date.parse(a.startDate), bm=Date.parse(b.startDate); if(!Number.isFinite(am)&&!Number.isFinite(bm)) return a.id.localeCompare(b.id); if(!Number.isFinite(am)) return 1; if(!Number.isFinite(bm)) return -1; return am-bm || a.id.localeCompare(b.id); });
  const rows = ordered.filter(e => filter === 'all' || filter === eventState(e,now)).map(e => '<button type="button" class="project-schedule-event" data-project-schedule-event-id="'+esc(e.id)+'" data-project-schedule-state="'+eventState(e,now)+'" data-project-schedule-action="open-event" data-c1-key="project-schedule-event-'+esc(e.id)+'"><strong>'+esc(e.name)+'</strong><small>'+esc(e.startDate)+'</small></button>').join('');
  let inspector = '';
  if (selected) { const e = events.find(x => x.id === selected); if (e) inspector = '<section class="project-schedule-event-inspector" data-project-schedule-inspector-event-id="'+esc(e.id)+'"><header><h3>'+esc(e.name)+'</h3><button type="button" data-project-schedule-action="close-event" data-c1-key="project-schedule-event-inspector-close">×</button></header><p>'+esc(e.description || 'No description')+'</p><div data-project-schedule-property="location">'+esc(e.properties.location ?? '—')+'</div><footer><button type="button" disabled aria-disabled="true" data-project-schedule-write-action="edit" data-project-schedule-write-refusal="'+PROJECT_SCHEDULE_WRITE_REFUSAL+'">Edit unavailable</button><button type="button" disabled aria-disabled="true" data-project-schedule-write-action="move" data-project-schedule-write-refusal="'+PROJECT_SCHEDULE_WRITE_REFUSAL+'">Move unavailable</button><button type="button" disabled aria-disabled="true" data-project-schedule-write-action="delete" data-project-schedule-write-refusal="'+PROJECT_SCHEDULE_WRITE_REFUSAL+'">Delete unavailable</button></footer></section>'; }
  const filters = (['all','upcoming','past','completed','invalid'] as const).map(f => '<button type="button" data-project-schedule-action="set-filter" data-project-schedule-filter="'+f+'" data-c1-key="project-schedule-filter-'+f+'" aria-pressed="'+(filter===f)+'">'+f.slice(0,1).toUpperCase()+f.slice(1)+'</button>').join('');
  return '<section class="project-workspace-panel project-schedule-panel" data-project-workspace-panel="schedule" data-project-schedule-write-authority="unavailable" data-c1-key="project-workspace-schedule"><header><h3>Schedule</h3><small>Project-scoped stored events</small></header><div class="project-schedule-filters">'+filters+'</div><div class="project-schedule-list">'+(rows || '<p class="empty-state">No project events.</p>')+'</div>'+inspector+'</section>';
}
export function bindProjectScheduleInteractions(root: HTMLElement, h: ProjectScheduleHandlers): void {
  root.addEventListener('click', e => { const c = (e.target as HTMLElement).closest<HTMLElement>('[data-project-schedule-action]'); if (!c) return; if (c.dataset.projectScheduleAction === 'set-filter') { const f=c.dataset.projectScheduleFilter; if(f==='all'||f==='upcoming'||f==='past'||f==='completed'||f==='invalid') h.setFilter(f); } else if(c.dataset.projectScheduleAction==='open-event'&&c.dataset.projectScheduleEventId) h.openEvent(c.dataset.projectScheduleEventId); else if(c.dataset.projectScheduleAction==='close-event') h.closeEvent(); });
  root.addEventListener('keydown', e => { if(e.key==='Escape'&&root.querySelector('[data-project-schedule-inspector-event-id]')) { e.preventDefault(); h.closeEvent(); } });
}
