import type { ProjectWorkspaceTab } from '../app/actionProtocol.js';
import type { Project, PropertySchema, ProximaState, Task } from '../domain/types.js';

export type ProjectsHubFilter = 'active' | 'archived';
export interface ProjectsHubCard { id:string; name:string; description:string; status:'active'|'archived'; ageDays:number|null; taskCount:number; overdueCount:number; highPriorityCount:number|null; nextDeadline:string|null; identityBackground:string|null; identityText:string|null; }
export interface ProjectsHubRenderOptions { state:ProximaState; selection:string; filter:ProjectsHubFilter; workspaceTab:ProjectWorkspaceTab; now:Date; }
export interface ProjectsHubHandlers { setFilter(filter:ProjectsHubFilter):void; openProject(projectId:string):void; showHub():void; }
const HIGH_PRIORITY_LABELS = new Set(['p1','high','high priority']);
function escapeHtml(value:unknown):string { return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'); }
function normaliseLabel(value:string):string { return value.trim().toLowerCase().replaceAll('_',' ').replaceAll('-',' ').replace(/\s+/g,' '); }
function isPrioritySchema(schema:PropertySchema):boolean { return normaliseLabel(schema.name).split(' ').includes('priority'); }
function valueMatchesHighPriority(value:unknown,schema?:PropertySchema):boolean { if(Array.isArray(value)) return value.some((item)=>valueMatchesHighPriority(item,schema)); if(value===1) return true; if(typeof value!=='string') return false; const normalised=normaliseLabel(value); if(HIGH_PRIORITY_LABELS.has(normalised)) return true; return schema?.options?.some((option)=>((option.id===value||normaliseLabel(option.name)===normalised)&&HIGH_PRIORITY_LABELS.has(normaliseLabel(option.name))))??false; }
function taskIsHighPriority(task:Task, prioritySchemas:readonly PropertySchema[]):boolean { for(const schema of prioritySchemas){ if(Object.prototype.hasOwnProperty.call(task.properties,schema.id)&&valueMatchesHighPriority(task.properties[schema.id],schema)) return true; } for(const [key,value] of Object.entries(task.properties)){ if(normaliseLabel(key).split(' ').includes('priority')&&valueMatchesHighPriority(value)) return true; } return false; }
function priorityIsRepresented(tasks:readonly Task[], prioritySchemas:readonly PropertySchema[]):boolean { return prioritySchemas.length>0||tasks.some((task)=>Object.keys(task.properties).some((key)=>normaliseLabel(key).split(' ').includes('priority'))); }
function validInstantMs(value:string|null):number|null { if(value===null) return null; const parsed=Date.parse(value); return Number.isFinite(parsed)?parsed:null; }
function ageInWholeDays(createdAt:string,nowMs:number):number|null { const createdMs=Date.parse(createdAt); if(!Number.isFinite(createdMs)) return null; return Math.max(0,Math.floor((nowMs-createdMs)/86_400_000)); }
function safeIdentityColor(value:string|undefined):string|null { if(!value) return null; const trimmed=value.trim(); return /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.test(trimmed)?trimmed:null; }
function cardForProject(state:ProximaState,project:Project,nowMs:number):ProjectsHubCard { const tasks=state.tasks.filter((task)=>task.projectId===project.id); const unfinished=tasks.filter((task)=>!task.isCompleted); const prioritySchemas=state.taskSchema.filter(isPrioritySchema); const represented=priorityIsRepresented(tasks,prioritySchemas); const overdueCount=unfinished.filter((task)=>{const deadlineMs=validInstantMs(task.deadline);return deadlineMs!==null&&deadlineMs<nowMs;}).length; const upcoming=unfinished.map((task)=>({task,deadlineMs:validInstantMs(task.deadline)})).filter((candidate):candidate is {task:Task;deadlineMs:number}=>candidate.deadlineMs!==null&&candidate.deadlineMs>=nowMs).sort((left,right)=>left.deadlineMs-right.deadlineMs||left.task.id.localeCompare(right.task.id)); return {id:project.id,name:project.name,description:project.description,status:project.status,ageDays:ageInWholeDays(project.createdAt,nowMs),taskCount:tasks.length,overdueCount,highPriorityCount:represented?unfinished.filter((task)=>taskIsHighPriority(task,prioritySchemas)).length:null,nextDeadline:upcoming[0]?.task.deadline??null,identityBackground:safeIdentityColor(project.tabBgColor),identityText:safeIdentityColor(project.tabTextColor)}; }
export function projectsHubCards(state:ProximaState,filter:ProjectsHubFilter,now:Date):ProjectsHubCard[] { const nowMs=now.getTime(); const effectiveNow=Number.isFinite(nowMs)?nowMs:0; return state.projects.filter((project)=>project.status===filter).sort((left,right)=>left.id.localeCompare(right.id)).map((project)=>cardForProject(state,project,effectiveNow)); }
function renderIdentity(card:ProjectsHubCard):string { if(card.identityBackground===null&&card.identityText===null)return ''; const style=['display:inline-block','width:12px','height:12px','border-radius:999px',card.identityBackground?`background-color:${card.identityBackground}`:'',card.identityText?`outline:2px solid ${card.identityText}`:''].filter(Boolean).join(';'); return `<span class="project-identity-swatch" data-project-identity-bg="${escapeHtml(card.identityBackground??'')}" data-project-identity-text="${escapeHtml(card.identityText??'')}" aria-label="Project visual identity" style="${style}"></span>`; }
function renderProjectCard(card:ProjectsHubCard):string { const age=card.ageDays===null?'Unknown':`${card.ageDays}d`; const priority=card.highPriorityCount===null?'':`<div><dt>P1 / high</dt><dd data-project-high-priority-count="${card.highPriorityCount}">${card.highPriorityCount}</dd></div>`; const nextDeadline=card.nextDeadline??'None'; return `<button type="button" class="project-hub-card" data-projects-hub-action="open-project" data-project-id="${escapeHtml(card.id)}" data-project-archive-state="${card.status}" data-project-age-days="${card.ageDays??''}" data-project-task-count="${card.taskCount}" data-project-overdue-count="${card.overdueCount}" data-project-next-deadline="${escapeHtml(card.nextDeadline??'')}" data-c1-key="project-hub-card-${escapeHtml(card.id)}"><header><span>${renderIdentity(card)}</span><span class="task-status">${card.status==='archived'?'Archived':'Active'}</span></header><h3>${escapeHtml(card.name)}</h3><p>${escapeHtml(card.description||'No description')}</p><dl><div><dt>Age</dt><dd>${escapeHtml(age)}</dd></div><div><dt>Tasks</dt><dd>${card.taskCount}</dd></div><div><dt>Overdue</dt><dd>${card.overdueCount}</dd></div>${priority}<div><dt>Next deadline</dt><dd>${escapeHtml(nextDeadline)}</dd></div></dl></button>`; }
function renderWorkspace(options:ProjectsHubRenderOptions,project:Project):string { const workspaceLabels:Record<ProjectWorkspaceTab,string>={notes:'Notes','task-board':'Task Board',backlog:'Backlog',deadlines:'Deadlines',schedule:'Schedule'}; return `<section class="surface projects-hub project-workspace" data-project-workspace-project-id="${escapeHtml(project.id)}" data-c1-key="projects-hub-region" aria-label="Projects Hub"><header class="surface-header"><div><p class="eyebrow">${project.status==='archived'?'Archived project':'Active project'}</p><h2>${escapeHtml(project.name)}</h2><p class="surface-description">${escapeHtml(project.description||'No description')}</p></div><button type="button" class="icon-button" data-projects-hub-action="show-hub" data-c1-key="project-hub-back">Projects</button></header><section data-c1-key="project-workspace-${escapeHtml(options.workspaceTab)}"><h3>${escapeHtml(workspaceLabels[options.workspaceTab])}</h3></section></section>`; }
export function renderProjectsHub(options:ProjectsHubRenderOptions):string { const selectedProject=options.state.projects.find((project)=>project.id===options.selection); if(selectedProject)return renderWorkspace(options,selectedProject); const cards=projectsHubCards(options.state,options.filter,options.now); return `<section class="surface projects-hub" data-projects-hub-filter="${options.filter}" data-c1-key="projects-hub-region" aria-label="Projects Hub"><header class="surface-header"><div><p class="eyebrow">Projects</p><h2>Projects Hub</h2><p class="surface-description">Read-only project inventory and project workspaces.</p></div><span class="surface-count">${cards.length} ${options.filter}</span></header><div class="calendar-controls" data-c1-key="project-hub-filters"><button type="button" data-projects-hub-action="set-filter" data-project-filter="active" data-c1-key="project-hub-filter-active" aria-pressed="${options.filter==='active'}">Active</button><button type="button" data-projects-hub-action="set-filter" data-project-filter="archived" data-c1-key="project-hub-filter-archived" aria-pressed="${options.filter==='archived'}">Archived</button></div><div class="project-hub-grid" data-c1-key="project-hub-cards">${cards.length>0?cards.map(renderProjectCard).join(''):`<p class="empty-state" data-c1-key="project-hub-empty">No ${options.filter} projects.</p>`}</div></section>`; }
export function bindProjectsHubInteractions(root:HTMLElement,handlers:ProjectsHubHandlers):void { root.addEventListener('click',(event)=>{ const control=(event.target as HTMLElement).closest<HTMLElement>('[data-projects-hub-action]'); if(!control||!root.contains(control))return; if(control.dataset.projectsHubAction==='set-filter'){const filter=control.dataset.projectFilter;if(filter==='active'||filter==='archived')handlers.setFilter(filter);return;} if(control.dataset.projectsHubAction==='open-project'){const projectId=control.dataset.projectId;if(projectId)handlers.openProject(projectId);return;} if(control.dataset.projectsHubAction==='show-hub')handlers.showHub(); }); }
