import type { ActionResult, ProjectWorkspaceTab } from '../app/actionProtocol.js';
import type { Project, PropertySchema, ProximaState, Task } from '../domain/types.js';
import type { ProjectNotesViewState } from './projectNotes.js';
import type { ProjectTaskBoardViewState } from './projectTaskBoard.js';
import type { ProjectWorkflowBoardViewState } from './projectWorkflowBoard.js';
import type { ProjectBacklogViewState } from './projectBacklog.js';
import type { ProjectDeadlinesViewState } from './projectDeadlines.js';
import type { ProjectScheduleViewState } from './projectSchedule.js';
import { renderProjectWorkspace } from './projectWorkspace.js';

export type ProjectsHubFilter = 'active' | 'archived';
export interface ProjectWriteView { refusal:string|null; feedback:string|null; feedbackRefusal?:string|null; }
export interface ProjectsHubCard { id:string; name:string; description:string; status:'active'|'archived'; ageDays:number|null; taskCount:number; overdueCount:number; highPriorityCount:number|null; nextDeadline:string|null; identityBackground:string|null; identityText:string|null; }
export interface ProjectCreateIntent { name:string; description:string; }
export interface ProjectsHubRenderOptions { state:ProximaState; selection:string; filter:ProjectsHubFilter; workspaceTab:ProjectWorkspaceTab; now:Date; newProjectOpen?:boolean; projectNotes?:ProjectNotesViewState; projectTaskBoard?:ProjectTaskBoardViewState; projectWorkflowBoard?:ProjectWorkflowBoardViewState; projectBacklog?:ProjectBacklogViewState; projectDeadlines?:ProjectDeadlinesViewState; projectSchedule?:ProjectScheduleViewState; projectWrites?:ProjectWriteView; }
export interface ProjectsHubHandlers { setFilter(filter:ProjectsHubFilter):void; openProject(projectId:string):void; showHub():void; openNewProject():void; closeNewProject():void; createProject(intent:ProjectCreateIntent):ActionResult|null; archiveProject(projectId:string):void; restoreProject(projectId:string):void; deleteProject(projectId:string):void; }
const HIGH_PRIORITY_LABELS = new Set(['p1','high','high priority']);
function escapeHtml(value:unknown):string { return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'); }
function normaliseLabel(value:string):string { return value.trim().toLowerCase().replaceAll('_',' ').replaceAll('-',' ').replace(/\s+/g,' '); }
function isPrioritySchema(schema:PropertySchema):boolean { return normaliseLabel(schema.name).split(' ').includes('priority'); }
function valueMatchesHighPriority(value:unknown,schema?:PropertySchema):boolean { if(Array.isArray(value)) return value.some((item)=>valueMatchesHighPriority(item,schema)); if(value===1) return true; if(typeof value!=='string') return false; const normalised=normaliseLabel(value); if(HIGH_PRIORITY_LABELS.has(normalised)) return true; return schema?.options?.some((option)=>((option.id===value||normaliseLabel(option.name)===normalised)&&HIGH_PRIORITY_LABELS.has(normaliseLabel(option.name))))??false; }
function taskIsHighPriority(task:Task, prioritySchemas:readonly PropertySchema[]):boolean { for(const schema of prioritySchemas){ if(Object.prototype.hasOwnProperty.call(task.properties,schema.id)&&valueMatchesHighPriority(task.properties[schema.id],schema)) return true; } for(const [key,value] of Object.entries(task.properties)){ if(normaliseLabel(key).split(' ').includes('priority')&&valueMatchesHighPriority(value)) return true; } return false; }
function priorityIsRepresented(tasks:readonly Task[], prioritySchemas:readonly PropertySchema[]):boolean { return prioritySchemas.length>0||tasks.some((task)=>Object.keys(task.properties).some((key)=>normaliseLabel(key).split(' ').includes('priority'))); }
function validInstantMs(value:string|null):number|null { if(value===null) return null; const parsed=Date.parse(value); return Number.isFinite(parsed)?parsed:null; }
function ageInWholeDays(createdAt:string,nowMs:number):number|null { const createdMs=Date.parse(createdAt); if(!Number.isFinite(createdMs)) return null; return Math.max(0,Math.floor((nowMs-createdMs)/86_400_000)); }
function safeIdentityColor(value:string|undefined):string|null { if(!value) return null; const trimmed=value.trim(); return /^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.test(trimmed)?trimmed:null; }
function cardForProject(state:ProximaState,project:Project,nowMs:number):ProjectsHubCard { const tasks=state.tasks.filter((task)=>task.projectId===project.id); const unfinished=tasks.filter((task)=>!task.isCompleted); const prioritySchemas=state.taskSchema.filter(isPrioritySchema); const represented=priorityIsRepresented(tasks,prioritySchemas); const overdueCount=unfinished.filter((task)=>{const deadlineMs=validInstantMs(task.deadline);return deadlineMs!==null&&deadlineMs<nowMs;}).length; const upcoming=unfinished.map((task)=>({task,deadlineMs:validInstantMs(task.deadline)})).filter((candidate):candidate is {task:Task;deadlineMs:number}=>candidate.deadlineMs!==null&&candidate.deadlineMs>=nowMs).sort((left,right)=>left.deadlineMs-right.deadlineMs||left.task.id.localeCompare(right.task.id)); return {id:project.id,name:project.name,description:project.description,status:project.status,ageDays:ageInWholeDays(project.createdAt,nowMs),taskCount:tasks.length,overdueCount,highPriorityCount:represented?unfinished.filter((task)=>taskIsHighPriority(task,prioritySchemas)).length:null,nextDeadline:upcoming[0]?.task.deadline??null,identityBackground:safeIdentityColor(project.tabBgColor),identityText:safeIdentityColor(project.tabTextColor)}; }
export function projectsHubCards(state:ProximaState,filter:ProjectsHubFilter,now:Date):ProjectsHubCard[] { const nowMs=now.getTime(); const effectiveNow=Number.isFinite(nowMs)?nowMs:0; return state.projects.filter((project)=>project.status===filter).sort((left,right)=>left.id.localeCompare(right.id)).map((project)=>cardForProject(state,project,effectiveNow)); }
function renderIdentity(card:ProjectsHubCard):string { if(card.identityBackground===null&&card.identityText===null)return ''; const style=['display:inline-block','width:12px','height:12px','border-radius:999px',card.identityBackground?`background-color:${card.identityBackground}`:'',card.identityText?`outline:2px solid ${card.identityText}`:''].filter(Boolean).join(';'); return `<span class="project-identity-swatch" data-project-identity-bg="${escapeHtml(card.identityBackground??'')}" data-project-identity-text="${escapeHtml(card.identityText??'')}" aria-label="Project visual identity" style="${style}"></span>`; }
const PROJECT_LIFECYCLE_UNAVAILABLE='Unavailable until record-store cutover';
/**
 * The lifecycle controls.
 *
 * Two states, and the difference is a resolved write path rather than a hardcoded constant: with one,
 * every control is a real button; without one, each is disabled and carries the typed reason beside
 * it. Delete is offered whenever the others are, because its refusal is an answer a reader can act on
 * — `policy-not-decided`, with the counts it would affect — rather than a feature that is missing.
 */
/**
 * The lifecycle line, in one place because two surfaces draw it.
 *
 * `available` is the whole distinction: with a resolved write path the code beside the sentence is
 * the last attempt's refusal, and without one it is the reason there are no controls to press. The
 * sentence is the caller's — an outcome's own words, or the operation's refusal — and only falls
 * back to the cutover notice when nobody has said anything and nothing can be done.
 */
function projectLifecycleLine(writes:ProjectWriteView|undefined):{available:boolean;refusal:string;feedback:string;code:string|null} { const refusal=writes?.refusal??'action-not-available'; const available=writes!==undefined&&(writes.refusal??null)===null; const feedback=writes?.feedback??(available?'':PROJECT_LIFECYCLE_UNAVAILABLE); const code=available?(writes?.feedbackRefusal??null):refusal; return { available, refusal, feedback, code }; }
function renderProjectLifecycleFeedback(writes:ProjectWriteView|undefined):string { const line=projectLifecycleLine(writes); return `<small data-project-lifecycle-feedback="${escapeHtml(line.code??'')}">${escapeHtml(line.feedback)}</small>`; }
/** The same sentence at the list level, so an outcome does not vanish with the card it moved. */
function renderProjectLifecycleReport(options:ProjectsHubRenderOptions):string { const line=projectLifecycleLine(options.projectWrites); if(line.feedback==='')return ''; return `<p class="project-lifecycle-report" data-c1-key="project-lifecycle-report" data-project-lifecycle-report="${escapeHtml(line.code??'')}">${escapeHtml(line.feedback)}</p>`; }
function renderProjectLifecycleControls(projectId:string,status:'active'|'archived',writes?:ProjectWriteView):string { const { available, refusal }=projectLifecycleLine(writes); const control=(action:'archive'|'restore'|'delete',label:string):string=>available?`<button type="button" data-project-lifecycle-action="${action}" data-project-id="${escapeHtml(projectId)}" data-c1-key="project-lifecycle-${action}-${escapeHtml(projectId)}">${label}</button>`:`<button type="button" disabled aria-disabled="true" data-project-lifecycle-action="${action}" data-project-id="${escapeHtml(projectId)}" data-project-lifecycle-refusal="${escapeHtml(refusal)}" data-c1-key="project-lifecycle-${action}-${escapeHtml(projectId)}" title="${PROJECT_LIFECYCLE_UNAVAILABLE}">${label}</button>`; const primary=status==='archived'?control('restore','Restore'):control('archive','Archive'); return `<div class="project-lifecycle-controls" data-project-lifecycle-state="${status}" data-project-lifecycle-writes="${available?'available':'unavailable'}" data-c1-key="project-lifecycle-controls-${escapeHtml(projectId)}">${primary}${control('delete','Delete')}${renderProjectLifecycleFeedback(writes)}</div>`; }
function renderProjectCard(card:ProjectsHubCard,writes?:ProjectWriteView):string { const age=card.ageDays===null?'Unknown':`${card.ageDays}d`; const priority=card.highPriorityCount===null?'':`<div><dt>P1 / high</dt><dd data-project-high-priority-count="${card.highPriorityCount}">${card.highPriorityCount}</dd></div>`; const nextDeadline=card.nextDeadline??'None'; return `<article class="project-hub-card-shell" data-c1-key="project-hub-card-shell-${escapeHtml(card.id)}"><button type="button" class="project-hub-card" data-projects-hub-action="open-project" data-project-id="${escapeHtml(card.id)}" data-project-archive-state="${card.status}" data-project-age-days="${card.ageDays??''}" data-project-task-count="${card.taskCount}" data-project-overdue-count="${card.overdueCount}" data-project-next-deadline="${escapeHtml(card.nextDeadline??'')}" data-c1-key="project-hub-card-${escapeHtml(card.id)}"><header><span>${renderIdentity(card)}</span><span class="task-status">${card.status==='archived'?'Archived':'Active'}</span></header><h3>${escapeHtml(card.name)}</h3><p>${escapeHtml(card.description||'No description')}</p><dl><div><dt>Age</dt><dd>${escapeHtml(age)}</dd></div><div><dt>Tasks</dt><dd>${card.taskCount}</dd></div><div><dt>Overdue</dt><dd>${card.overdueCount}</dd></div>${priority}<div><dt>Next deadline</dt><dd>${escapeHtml(nextDeadline)}</dd></div></dl></button>${renderProjectLifecycleControls(card.id,card.status,writes)}</article>`; }
function renderWorkspace(options:ProjectsHubRenderOptions,project:Project):string { return `<section class="surface projects-hub project-workspace" data-project-workspace-project-id="${escapeHtml(project.id)}" data-c1-key="projects-hub-region" aria-label="Projects Hub"><header class="surface-header"><div><p class="eyebrow">${project.status==='archived'?'Archived project':'Active project'}</p><h2>${escapeHtml(project.name)}</h2><p class="surface-description">${escapeHtml(project.description||'No description')}</p></div><div><button type="button" class="icon-button" data-projects-hub-action="show-hub" data-c1-key="project-hub-back">Projects</button>${renderProjectLifecycleControls(project.id,project.status,options.projectWrites)}</div></header>${renderProjectWorkspace({state:options.state,project,tab:options.workspaceTab,now:options.now,notes:options.projectNotes,taskBoard:options.projectTaskBoard,workflowBoard:options.projectWorkflowBoard,backlog:options.projectBacklog,deadlines:options.projectDeadlines,schedule:options.projectSchedule})}</section>`; }
function renderProjectCreateModal():string { return `<div class="modal-backdrop" data-c1-key="project-create-backdrop"><section class="task-modal" role="dialog" aria-modal="true" aria-label="New Project" data-project-editor-mode="create" data-c1-key="project-create-modal"><header class="surface-header"><div><p class="eyebrow">Project</p><h3>New Project</h3></div><button type="button" class="icon-button" data-projects-hub-action="close-new-project" data-c1-key="project-create-close" aria-label="Close New Project">×</button></header><label>Name<input data-c1-key="project-create-name" value=""></label><label>Description<textarea data-c1-key="project-create-description"></textarea></label><div class="calendar-controls"><button type="button" data-projects-hub-action="close-new-project" data-c1-key="project-create-cancel">Cancel</button><button type="button" data-projects-hub-action="save-new-project" data-c1-key="project-create-save">Save</button></div></section></div>`; }
export function renderProjectsHub(options:ProjectsHubRenderOptions):string { const selectedProject=options.state.projects.find((project)=>project.id===options.selection); if(selectedProject)return renderWorkspace(options,selectedProject); const cards=projectsHubCards(options.state,options.filter,options.now); const createModal=options.newProjectOpen===true?renderProjectCreateModal():''; return `<section class="surface projects-hub" data-projects-hub-filter="${options.filter}" data-c1-key="projects-hub-region" aria-label="Projects Hub"><header class="surface-header"><div><p class="eyebrow">Projects</p><h2>Projects Hub</h2><p class="surface-description">Read-only project inventory and project workspaces.</p></div><div class="calendar-controls"><span class="surface-count">${cards.length} ${options.filter}</span><button type="button" data-projects-hub-action="open-new-project" data-c1-key="project-create-open">New Project</button></div></header><div class="calendar-controls" data-c1-key="project-hub-filters"><button type="button" data-projects-hub-action="set-filter" data-project-filter="active" data-c1-key="project-hub-filter-active" aria-pressed="${options.filter==='active'}">Active</button><button type="button" data-projects-hub-action="set-filter" data-project-filter="archived" data-c1-key="project-hub-filter-archived" aria-pressed="${options.filter==='archived'}">Archived</button></div>${renderProjectLifecycleReport(options)}<div class="project-hub-grid" data-c1-key="project-hub-cards">${cards.length>0?cards.map((card)=>renderProjectCard(card,options.projectWrites)).join(''):`<p class="empty-state" data-c1-key="project-hub-empty">No ${options.filter} projects.</p>`}</div>${createModal}</section>`; }
export function bindProjectsHubInteractions(root:HTMLElement,handlers:ProjectsHubHandlers):void { root.addEventListener('click',(event)=>{ const life=(event.target as HTMLElement).closest<HTMLElement>('[data-project-lifecycle-action]'); if(life&&root.contains(life)&&!life.hasAttribute('disabled')){const action=life.dataset.projectLifecycleAction;const projectId=life.dataset.projectId;if(projectId){if(action==='archive')handlers.archiveProject(projectId);else if(action==='restore')handlers.restoreProject(projectId);else if(action==='delete')handlers.deleteProject(projectId);}return;} const control=(event.target as HTMLElement).closest<HTMLElement>('[data-projects-hub-action]'); if(!control||!root.contains(control))return; if(control.dataset.projectsHubAction==='set-filter'){const filter=control.dataset.projectFilter;if(filter==='active'||filter==='archived')handlers.setFilter(filter);return;} if(control.dataset.projectsHubAction==='open-project'){const projectId=control.dataset.projectId;if(projectId)handlers.openProject(projectId);return;} if(control.dataset.projectsHubAction==='show-hub'){handlers.showHub();return;} if(control.dataset.projectsHubAction==='open-new-project'){handlers.openNewProject();return;} if(control.dataset.projectsHubAction==='close-new-project'){handlers.closeNewProject();return;} if(control.dataset.projectsHubAction==='save-new-project'){const modal=control.closest<HTMLElement>('[data-project-editor-mode="create"]');const name=modal?.querySelector<HTMLInputElement>('[data-c1-key="project-create-name"]');const description=modal?.querySelector<HTMLTextAreaElement>('[data-c1-key="project-create-description"]');if(!modal||!name||!description)return;const result=handlers.createProject({name:name.value,description:description.value});if(result&&!result.ok)modal.dataset.projectCreateRefusal=result.error.code;else delete modal.dataset.projectCreateRefusal;} }); root.addEventListener('keydown',(event)=>{if(event.key==='Escape'&&root.querySelector('[data-project-editor-mode="create"]')){event.preventDefault();handlers.closeNewProject();}}); }
