import type { ProjectWorkspaceTab } from '../app/actionProtocol.js';
import type { CalendarEvent, Project, ProximaState, StatusDefinition, Task } from '../domain/types.js';
import { EMPTY_PROJECT_NOTES_VIEW, renderProjectNotes, type ProjectNotesViewState } from './projectNotes.js';
import { EMPTY_PROJECT_TASK_BOARD_VIEW, renderProjectTaskBoard, type ProjectTaskBoardViewState } from './projectTaskBoard.js';
import { EMPTY_PROJECT_BACKLOG_VIEW, renderProjectBacklog, type ProjectBacklogViewState } from './projectBacklog.js';
import { EMPTY_PROJECT_DEADLINES_VIEW, renderProjectDeadlines, type ProjectDeadlinesViewState } from './projectDeadlines.js';
import { EMPTY_PROJECT_SCHEDULE_VIEW, renderProjectSchedule, type ProjectScheduleViewState } from './projectSchedule.js';
import { deadlineCalendarProjection } from './timekeepingCockpit.js';
export interface ProjectWorkspaceRenderOptions { state:ProximaState; project:Project; tab:ProjectWorkspaceTab; now:Date; notes?:ProjectNotesViewState; taskBoard?:ProjectTaskBoardViewState; backlog?:ProjectBacklogViewState; deadlines?:ProjectDeadlinesViewState; schedule?:ProjectScheduleViewState; }
function escapeHtml(value:unknown):string { return String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;'); }
function projectTasks(state:ProximaState,projectId:string):Task[]{ return state.tasks.filter((task)=>task.projectId===projectId); }
function projectEvents(state:ProximaState,projectId:string):CalendarEvent[]{ return state.events.filter((event)=>event.projectId===projectId); }
function taskOrder(left:Task,right:Task):number { return (Number(left.orderIndex)||0)-(Number(right.orderIndex)||0)||left.id.localeCompare(right.id); }
function safeStatusColor(status:StatusDefinition|undefined):string|null { const value=status?.color?.trim(); return value&&/^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$/.test(value)?value:null; }
function statusColumns(state:ProximaState,tasks:readonly Task[]):Array<{id:string;label:string;status:StatusDefinition|undefined}>{ const definitions=new Map(state.statuses.map((status)=>[status.id,status])); const ids:string[]=[]; const seen=new Set<string>(); for(const status of state.statuses){if(!seen.has(status.id)){seen.add(status.id);ids.push(status.id);}} for(const task of tasks){if(!seen.has(task.status)){seen.add(task.status);ids.push(task.status);}} return ids.map((id)=>({id,label:definitions.get(id)?.name??id,status:definitions.get(id)})); }
function renderTaskBoard(state:ProximaState,tasks:readonly Task[]):string { const columns=statusColumns(state,tasks).map((column)=>{const items=tasks.filter((task)=>task.status===column.id).sort(taskOrder);const color=safeStatusColor(column.status);const style=color?` style="border-top:3px solid ${color};"`:'';const cards=items.map((task)=>`<article class="project-board-task${task.isCompleted?' completed':''}" data-project-board-task-id="${escapeHtml(task.id)}" data-project-board-status="${escapeHtml(column.id)}" data-project-board-order="${Number(task.orderIndex)||0}" data-c1-key="project-board-task-${escapeHtml(task.id)}"><strong>${escapeHtml(task.name)}</strong><small>${escapeHtml(task.deadline??'No deadline')}</small></article>`).join('');return `<section class="project-board-column" data-project-board-status-column="${escapeHtml(column.id)}" data-project-status-color="${escapeHtml(color??'')}" data-c1-key="project-board-column-${escapeHtml(column.id)}"${style}><header><strong>${escapeHtml(column.label)}</strong><span>${items.length}</span></header>${cards||'<p class="empty-state">No tasks.</p>'}</section>`;}).join(''); return `<section class="project-workspace-panel project-task-board-panel" data-project-workspace-panel="task-board" data-c1-key="project-workspace-task-board"><header><h3>Task Board</h3><small>Read-only current status projection</small></header><div class="project-board-columns">${columns||'<p class="empty-state" data-c1-key="project-board-empty">No project tasks.</p>'}</div></section>`; }
function renderBacklog(tasks:readonly Task[]):string { const rows=[...tasks].sort(taskOrder).map((task)=>`<article class="project-backlog-task${task.isCompleted?' completed':''}" data-project-backlog-task-id="${escapeHtml(task.id)}" data-project-backlog-order="${Number(task.orderIndex)||0}" data-c1-key="project-backlog-task-${escapeHtml(task.id)}"><strong>${escapeHtml(task.name)}</strong><small>Status ${escapeHtml(task.status)} · ${escapeHtml(task.deadline??'No deadline')}</small></article>`).join(''); return `<section class="project-workspace-panel project-backlog-panel" data-project-workspace-panel="backlog" data-c1-key="project-workspace-backlog"><header><h3>Backlog</h3><small>${tasks.length} project task${tasks.length===1?'':'s'}</small></header>${rows||'<p class="empty-state" data-c1-key="project-backlog-empty">No project tasks.</p>'}</section>`; }
function renderDeadlines(tasks:readonly Task[],now:Date):string { const tasksById=new Map(tasks.map((task)=>[task.id,task])); const entries=deadlineCalendarProjection(tasks,now); const rows=entries.map((entry)=>{const task=tasksById.get(entry.taskId);if(!task)return '';return `<article class="project-deadline-task${task.isCompleted?' completed':''}" data-project-deadline-task-id="${escapeHtml(task.id)}" data-project-deadline-day="${escapeHtml(entry.dayKey)}" data-project-deadline-value="${escapeHtml(entry.deadline)}" data-project-deadline-remaining-ms="${entry.remainingMs}" data-c1-key="project-deadline-task-${escapeHtml(task.id)}"><strong>${escapeHtml(task.name)}</strong><small>${escapeHtml(entry.deadline)}</small></article>`;}).join(''); return `<section class="project-workspace-panel project-deadlines-panel" data-project-workspace-panel="deadlines" data-project-deadline-projection="timekeeping" data-c1-key="project-workspace-deadlines"><header><h3>Deadlines</h3><small>Project-scoped Timekeeping deadline projection</small></header>${rows||'<p class="empty-state" data-c1-key="project-deadlines-empty">No project deadlines.</p>'}</section>`; }
function eventOrder(left:CalendarEvent,right:CalendarEvent):number { return left.startDate.localeCompare(right.startDate)||left.deadline.localeCompare(right.deadline)||left.id.localeCompare(right.id); }
function renderSchedule(events:readonly CalendarEvent[]):string { const rows=[...events].sort(eventOrder).map((event)=>`<article class="project-schedule-event${event.isCompleted?' completed':''}" data-project-schedule-event-id="${escapeHtml(event.id)}" data-project-schedule-start="${escapeHtml(event.startDate)}" data-project-schedule-end="${escapeHtml(event.deadline)}" data-c1-key="project-schedule-event-${escapeHtml(event.id)}"><strong>${escapeHtml(event.name)}</strong><small>${escapeHtml(event.startDate)} → ${escapeHtml(event.deadline)}</small></article>`).join(''); return `<section class="project-workspace-panel project-schedule-panel" data-project-workspace-panel="schedule" data-c1-key="project-workspace-schedule"><header><h3>Schedule</h3><small>${events.length} project event${events.length===1?'':'s'}</small></header>${rows||'<p class="empty-state" data-c1-key="project-schedule-empty">No project events.</p>'}</section>`; }
export function renderProjectWorkspace(options:ProjectWorkspaceRenderOptions):string { const tasks=projectTasks(options.state,options.project.id); if(options.tab==='notes')return renderProjectNotes(options.project,options.notes??EMPTY_PROJECT_NOTES_VIEW); if(options.tab==='task-board')return renderProjectTaskBoard(options.state,options.project,options.taskBoard??EMPTY_PROJECT_TASK_BOARD_VIEW); if(options.tab==='backlog')return renderProjectBacklog(options.state,options.project,options.backlog??EMPTY_PROJECT_BACKLOG_VIEW); if(options.tab==='deadlines')return renderProjectDeadlines(options.state,options.project,options.now,options.deadlines??EMPTY_PROJECT_DEADLINES_VIEW); return renderProjectSchedule(options.state,options.project,options.now,options.schedule??EMPTY_PROJECT_SCHEDULE_VIEW); }
