import { coerceScalar } from '../domain/frontmatter.js';
import { readOptionalDate, type FieldIssue } from '../domain/validation.js';
import type { VaultMutationCoordinator, VaultMutationOutcome } from './vaultMutation.js';

export interface CreateEventInput { id: string; name: string; createdAt: string; project?: string; startDate?: string; deadline?: string; isCompleted?: boolean; body?: string; }
export interface CreateEventOptions { input: CreateEventInput; coordinator: VaultMutationCoordinator; eventsDirectory?: string; maxBytes?: number; }
export type EventCreationOutcome = VaultMutationOutcome | { ok: false; reason: 'invalid-value' | 'input-too-large' | 'invalid-path' };
const MAX = 4096; const RESERVED = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$/i;
function safeText(value: unknown, nonEmpty = true): value is string { return typeof value === 'string' && (!nonEmpty || value.length > 0) && value.length <= MAX && !/[\u0000-\u001F\u007F\r\n]/u.test(value); }
function safePlain(value: string): boolean { return value.length > 0 && !/^[\-?:,\[\]{}#&*!|>'"%@`]/.test(value) && !/[ \t]#/.test(value) && !/:[ \t]/.test(value) && typeof coerceScalar(value) === 'string' && coerceScalar(value) === value; }
function yamlString(value: string): string { return safePlain(value) ? value : `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`; }
function validDate(value: unknown): value is string { if (typeof value !== 'string') return false; const issues: FieldIssue[] = []; return readOptionalDate(value, 'date', issues) !== null && issues.length === 0; }
function validDirectory(directory: string): boolean { if (typeof directory !== 'string' || directory.length === 0 || directory.length > 260 || directory.startsWith('/') || /^[A-Za-z]:[\\/]/.test(directory)) return false; return directory.replaceAll('\\', '/').split('/').every((part) => part.length > 0 && part !== '.' && part !== '..'); }
function validInput(input: unknown): input is CreateEventInput { if (typeof input !== 'object' || input === null) return false; const c = input as CreateEventInput; if (!safeText(c.id) || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(c.id) || RESERVED.test(c.id)) return false; if (!safeText(c.name) || !safeText(c.createdAt) || !validDate(c.createdAt)) return false; if (c.project !== undefined && !safeText(c.project)) return false; if (c.startDate !== undefined && !validDate(c.startDate)) return false; if (c.deadline !== undefined && !validDate(c.deadline)) return false; if (c.isCompleted !== undefined && typeof c.isCompleted !== 'boolean') return false; return c.body === undefined || (typeof c.body === 'string' && !/[\u0000\u007F]/u.test(c.body)); }
function canonicalBytes(input: CreateEventInput, maxBytes: number): Uint8Array | null { const lines = [`id: ${yamlString(input.id)}`, `name: ${yamlString(input.name)}`, `createdAt: ${yamlString(input.createdAt)}`]; if (input.project !== undefined) lines.push(`project: ${yamlString(input.project)}`); if (input.startDate !== undefined) lines.push(`startDate: ${yamlString(input.startDate)}`); if (input.deadline !== undefined) lines.push(`deadline: ${yamlString(input.deadline)}`); if (input.isCompleted !== undefined) lines.push(`isCompleted: ${String(input.isCompleted)}`); const bytes = new TextEncoder().encode(`---\n${lines.join('\n')}\n---\n${input.body ?? ''}`); return bytes.byteLength <= maxBytes ? bytes : null; }

/** Create exactly one canonical event file through exclusive createIfAbsent. */
export async function createEvent(options: CreateEventOptions): Promise<EventCreationOutcome> { const maxBytes = Math.max(1, Math.floor(options.maxBytes ?? 4 * 1024 * 1024)); const directory = options.eventsDirectory ?? 'Proxima/events'; if (!validInput(options.input)) return { ok: false, reason: 'invalid-value' }; if (!validDirectory(directory)) return { ok: false, reason: 'invalid-path' }; if (options.input.body !== undefined && new TextEncoder().encode(options.input.body).byteLength > maxBytes) return { ok: false, reason: 'input-too-large' }; const bytes = canonicalBytes(options.input, maxBytes); if (!bytes) return { ok: false, reason: 'input-too-large' }; return options.coordinator.execute({ kind: 'create', path: `${directory.replaceAll('\\', '/')}/${options.input.id}.md`, bytes }); }
