import type { SourceRef } from '../domain/records.js';
import type { VaultMutationCoordinator, VaultMutationOutcome } from './vaultMutation.js';
export interface EventSourceIdentity { id: string; source: SourceRef; }
export interface RenameEventSourceOptions { event: EventSourceIdentity; newFileStem: string; coordinator: VaultMutationCoordinator; eventsDirectory?: string; }
export interface DeleteEventSourceOptions { event: EventSourceIdentity; coordinator: VaultMutationCoordinator; eventsDirectory?: string; }
export type EventSourceLifecycleOutcome = VaultMutationOutcome | { ok: false; reason: 'invalid-provenance' | 'invalid-name' | 'rename-requires-explicit-id' };
const SAFE = /^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
function validDirectory(d: string): boolean { return typeof d === 'string' && d.length > 0 && d.length <= 260 && !d.startsWith('/') && !/^[A-Za-z]:\//.test(d) && d.replaceAll('\\','/').split('/').every((p)=>p.length>0&&p!=='.'&&p!=='..'); }
function validEvent(e: unknown, d: string): e is EventSourceIdentity { if(typeof e!=='object'||e===null)return false; const c=e as Partial<EventSourceIdentity>; const s=c.source as Partial<SourceRef>|undefined; if(typeof c.id!=='string'||c.id.length===0||c.id.length>200||!s||s.kind!=='event'||(s.idOrigin!=='filename'&&s.idOrigin!=='frontmatter')||typeof s.path!=='string'||s.path.length===0||s.path.length>260||typeof s.revision!=='string'||s.revision.length===0||s.revision.length>400)return false; const p=s.path.replaceAll('\\','/'), pre=`${d.replaceAll('\\','/')}/`, rest=p.slice(pre.length); return p.startsWith(pre)&&!rest.includes('/')&&rest.toLowerCase().endsWith('.md')&&!p.split('/').some(x=>!x||x==='.'||x==='..'); }
function portable(s:string):boolean { const b=(s.split('.')[0]??'').toUpperCase(); return !['CON','PRN','AUX','NUL'].includes(b)&&!/^(COM|LPT)[1-9]$/.test(b); }
export async function renameEventSource(o: RenameEventSourceOptions): Promise<EventSourceLifecycleOutcome> { const d=(o.eventsDirectory??'Proxima/events').replaceAll('\\','/'); if(!validEvent(o.event,d)||!validDirectory(d))return {ok:false,reason:'invalid-provenance'}; if(o.event.source.idOrigin!=='frontmatter')return {ok:false,reason:'rename-requires-explicit-id'}; if(typeof o.newFileStem!=='string'||!SAFE.test(o.newFileStem)||!portable(o.newFileStem))return {ok:false,reason:'invalid-name'}; const p=o.event.source.path.replaceAll('\\','/'), dest=`${p.slice(0,p.lastIndexOf('/')+1)}${o.newFileStem}.md`; return o.coordinator.execute({kind:'move',from:p,to:dest,expectedRevision:o.event.source.revision}); }
export async function deleteEventSource(o: DeleteEventSourceOptions): Promise<EventSourceLifecycleOutcome> { const d=(o.eventsDirectory??'Proxima/events').replaceAll('\\','/'); if(!validEvent(o.event,d)||!validDirectory(d))return {ok:false,reason:'invalid-provenance'}; return o.coordinator.execute({kind:'delete',path:o.event.source.path.replaceAll('\\','/'),expectedRevision:o.event.source.revision}); }
