import type { SourceRef } from '../domain/records.js';
import type { VaultReader } from '../ports/vault.js';
import type { VaultMutationCoordinator, VaultMutationOutcome } from './vaultMutation.js';
import { planProjectLinkedFoldersPromotion, type SourcePatchFailureReason } from './sourcePreservingMarkdown.js';
export interface PromoteProjectLinkedFoldersOptions { project: { id: string; source: SourceRef }; reader: VaultReader; coordinator: VaultMutationCoordinator; projectsDirectory?: string; maxBytes?: number; }
export type ProjectLinkedFoldersPromotionOutcome = VaultMutationOutcome | { ok: true; noOp: true; path: string; revision: string } | { ok: false; reason: SourcePatchFailureReason | 'invalid-provenance' | 'binary-read-unavailable' | 'missing' };
function validDirectory(directory: string): boolean { return typeof directory === 'string' && directory.length > 0 && directory.length <= 260 && !directory.startsWith('/') && !/^[A-Za-z]:\//.test(directory) && directory.replaceAll('\\', '/').split('/').every((part) => part.length > 0 && part !== '.' && part !== '..'); }
function validSource(source: unknown, directory: string): source is SourceRef { if (typeof source !== 'object' || source === null) return false; const s = source as Partial<SourceRef>; if (s.kind !== 'project' || typeof s.path !== 'string' || s.path.length === 0 || s.path.length > 260 || typeof s.revision !== 'string' || s.revision.length === 0 || s.revision.length > 400) return false; const path = s.path.replaceAll('\\', '/'); const prefix = `${directory.replaceAll('\\', '/')}/`; if (!path.startsWith(prefix) || path.split('/').some((part) => !part || part === '.' || part === '..')) return false; const parts = path.slice(prefix.length).split('/'); return (parts.length === 1 && parts[0]!.toLowerCase().endsWith('.md')) || (parts.length === 2 && parts[1]!.toLowerCase() === 'index.md'); }
/** Promote legacy linked-folder source representation; no caller replacement list is accepted. */
export async function promoteProjectLinkedFolders(options: PromoteProjectLinkedFoldersOptions): Promise<ProjectLinkedFoldersPromotionOutcome> { const directory = (options.projectsDirectory ?? 'Proxima/projects').replaceAll('\\', '/'); if (!validDirectory(directory) || typeof options.project !== 'object' || options.project === null || typeof options.project.id !== 'string' || options.project.id.length === 0 || options.project.id.length > 200 || !validSource(options.project.source, directory)) return { ok: false, reason: 'invalid-provenance' }; const source = options.project.source; if (typeof options.reader.readBinary !== 'function') return { ok: false, reason: 'binary-read-unavailable' }; const maxBytes = Math.max(1, Math.floor(options.maxBytes ?? 4 * 1024 * 1024)); let file; try { file = await options.reader.readBinary(source.path, maxBytes); } catch { return { ok: false, reason: 'missing' }; } if (file.bytes.byteLength > maxBytes) return { ok: false, reason: 'source-too-large' }; const patch = planProjectLinkedFoldersPromotion(file.bytes, maxBytes); if (!patch.ok && (patch.reason === 'target-missing' || patch.reason === 'target-unsupported')) { const text = new TextDecoder('utf-8', { fatal: false }).decode(file.bytes); if (/^\s*linkedFolders:\s*\[/m.test(text) || !/^\s*linkedFolder(?:s)?:/m.test(text)) return { ok: true, noOp: true, path: source.path, revision: file.revision }; } if (!patch.ok) return patch; return options.coordinator.execute({ kind: 'update', path: source.path, bytes: patch.bytes, expectedRevision: source.revision }); }
