import { coerceScalar } from '../domain/frontmatter.js';
import { readOptionalDate, type FieldIssue } from '../domain/validation.js';
import type { VaultMutationCoordinator, VaultMutationOutcome } from './vaultMutation.js';

export interface CreateProjectInput { id: string; name: string; createdAt: string; status?: 'active' | 'archived'; projectType?: 'task' | 'schedule'; tabBgColor?: string; tabTextColor?: string; description?: string; body?: string; }
export interface CreateProjectOptions { input: CreateProjectInput; coordinator: VaultMutationCoordinator; projectsDirectory?: string; maxBytes?: number; }
export type ProjectCreationOutcome = VaultMutationOutcome | { ok: false; reason: 'invalid-value' | 'input-too-large' | 'invalid-path' };
const MAX = 4096; const RESERVED = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])(?:\..*)?$/i;
function safeText(value: unknown, nonEmpty = true): value is string { return typeof value === 'string' && (!nonEmpty || value.length > 0) && value.length <= MAX && !/[\u0000-\u001F\u007F\r\n]/u.test(value); }
function safePlain(value: string): boolean { return value.length > 0 && !/^[\-?:,\[\]{}#&*!|>'"%@`]/.test(value) && !/[ \t]#/.test(value) && !/:[ \t]/.test(value) && typeof coerceScalar(value) === 'string' && coerceScalar(value) === value; }
function yamlString(value: string): string { return safePlain(value) ? value : `"${value.replaceAll('\\', '\\\\').replaceAll('"', '\\"')}"`; }
function validDate(value: unknown): value is string { if (typeof value !== 'string') return false; const issues: FieldIssue[] = []; return readOptionalDate(value, 'date', issues) !== null && issues.length === 0; }
function validDirectory(directory: string): boolean { if (typeof directory !== 'string' || directory.length === 0 || directory.length > 260 || directory.startsWith('/') || /^[A-Za-z]:[\\/]/.test(directory)) return false; return directory.replaceAll('\\', '/').split('/').every((part) => part.length > 0 && part !== '.' && part !== '..'); }
function validInput(input: unknown): input is CreateProjectInput { if (typeof input !== 'object' || input === null) return false; const c = input as CreateProjectInput; if (!safeText(c.id) || !/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(c.id) || RESERVED.test(c.id) || !safeText(c.name) || !safeText(c.createdAt) || !validDate(c.createdAt)) return false; if (c.status !== undefined && c.status !== 'active' && c.status !== 'archived') return false; if (c.projectType !== undefined && c.projectType !== 'task' && c.projectType !== 'schedule') return false; if (c.tabBgColor !== undefined && !safeText(c.tabBgColor)) return false; if (c.tabTextColor !== undefined && !safeText(c.tabTextColor)) return false; if (c.description !== undefined && !safeText(c.description)) return false; return c.body === undefined || (typeof c.body === 'string' && !/[\u0000\u007F]/u.test(c.body)); }
function canonicalBytes(c: CreateProjectInput, maxBytes: number): Uint8Array | null { const lines = [`id: ${yamlString(c.id)}`, `name: ${yamlString(c.name)}`, `createdAt: ${yamlString(c.createdAt)}`]; if (c.status !== undefined) lines.push(`status: ${c.status}`); if (c.projectType !== undefined) lines.push(`projectType: ${c.projectType}`); if (c.tabBgColor !== undefined) lines.push(`tabBgColor: ${yamlString(c.tabBgColor)}`); if (c.tabTextColor !== undefined) lines.push(`tabTextColor: ${yamlString(c.tabTextColor)}`); if (c.description !== undefined) lines.push(`description: ${yamlString(c.description)}`); const bytes = new TextEncoder().encode(`---\n${lines.join('\n')}\n---\n${c.body ?? ''}`); return bytes.byteLength <= maxBytes ? bytes : null; }

/** Create exactly one canonical flat project file through exclusive createIfAbsent. */
export async function createProject(options: CreateProjectOptions): Promise<ProjectCreationOutcome> { const maxBytes = Math.max(1, Math.floor(options.maxBytes ?? 4 * 1024 * 1024)); const directory = options.projectsDirectory ?? 'Proxima/projects'; if (!validInput(options.input)) return { ok: false, reason: 'invalid-value' }; if (!validDirectory(directory)) return { ok: false, reason: 'invalid-path' }; if (options.input.body !== undefined && new TextEncoder().encode(options.input.body).byteLength > maxBytes) return { ok: false, reason: 'input-too-large' }; const bytes = canonicalBytes(options.input, maxBytes); if (!bytes) return { ok: false, reason: 'input-too-large' }; return options.coordinator.execute({ kind: 'create', path: `${directory.replaceAll('\\', '/')}/${options.input.id}.md`, bytes }); }
