import type { SourceRef } from '../domain/records.js';
import type { VaultMutationCoordinator, VaultMutationOutcome } from './vaultMutation.js';
export interface ProjectSourceIdentity { id: string; source: SourceRef; }
export interface RenameProjectSourceOptions { project: ProjectSourceIdentity; newFileStem: string; coordinator: VaultMutationCoordinator; projectsDirectory?: string; }
export interface DeleteProjectSourceOptions { project: ProjectSourceIdentity; coordinator: VaultMutationCoordinator; projectsDirectory?: string; }
export type ProjectSourceLifecycleOutcome = VaultMutationOutcome | { ok: false; reason: 'invalid-provenance' | 'invalid-name' | 'rename-requires-explicit-id' };
const SAFE=/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/;
function dir(d:string):boolean{return typeof d==='string'&&d.length>0&&d.length<=260&&!d.startsWith('/')&&!/^[A-Za-z]:\//.test(d)&&d.replaceAll('\\','/').split('/').every(p=>p.length>0&&p!=='.'&&p!=='..');}
function valid(p:unknown,d:string):p is ProjectSourceIdentity{if(typeof p!=='object'||p===null)return false;const c=p as Partial<ProjectSourceIdentity>,s=c.source as Partial<SourceRef>|undefined;if(typeof c.id!=='string'||c.id.length===0||c.id.length>200||!s||s.kind!=='project'||!['filename','folder','frontmatter'].includes(s.idOrigin as string)||typeof s.path!=='string'||s.path.length===0||s.path.length>260||typeof s.revision!=='string'||s.revision.length===0||s.revision.length>400)return false;const path=s.path.replaceAll('\\','/'),pre=`${d.replaceAll('\\','/')}/`;if(!path.startsWith(pre)||path.split('/').some(x=>!x||x==='.'||x==='..'))return false;const parts=path.slice(pre.length).split('/');return(parts.length===1&&parts[0]!.toLowerCase().endsWith('.md'))||(parts.length===2&&parts[1]!.toLowerCase()==='index.md');}
function portable(s:string):boolean{const b=(s.split('.')[0]??'').toUpperCase();return !['CON','PRN','AUX','NUL'].includes(b)&&!/^(COM|LPT)[1-9]$/.test(b);}
export async function renameProjectSource(o:RenameProjectSourceOptions):Promise<ProjectSourceLifecycleOutcome>{const d=(o.projectsDirectory??'Proxima/projects').replaceAll('\\','/');if(!dir(d)||!valid(o.project,d))return{ok:false,reason:'invalid-provenance'};if(o.project.source.idOrigin!=='frontmatter')return{ok:false,reason:'rename-requires-explicit-id'};if(typeof o.newFileStem!=='string'||!SAFE.test(o.newFileStem)||!portable(o.newFileStem))return{ok:false,reason:'invalid-name'};const p=o.project.source.path.replaceAll('\\','/'),parts=p.slice(`${d}/`.length).split('/');const dest=parts.length===1?`${d}/${o.newFileStem}.md`:`${d}/${o.newFileStem}/index.md`;return o.coordinator.execute({kind:'move',from:p,to:dest,expectedRevision:o.project.source.revision});}
export async function deleteProjectSource(o:DeleteProjectSourceOptions):Promise<ProjectSourceLifecycleOutcome>{const d=(o.projectsDirectory??'Proxima/projects').replaceAll('\\','/');if(!dir(d)||!valid(o.project,d))return{ok:false,reason:'invalid-provenance'};return o.coordinator.execute({kind:'delete',path:o.project.source.path.replaceAll('\\','/'),expectedRevision:o.project.source.revision});}
