import type { SourceRef } from '../domain/records.js';
import type { VaultReader } from '../ports/vault.js';
import type { VaultMutationCoordinator, VaultMutationOutcome } from './vaultMutation.js';
import { planProjectLinkedFoldersRemove, planProjectLinkedFoldersSet, type ProjectLinkedFolderValue, type SourcePatchFailureReason } from './sourcePreservingMarkdown.js';

export type ProjectLinkedFoldersMutation = { kind: 'set'; folders: ProjectLinkedFolderValue[] } | { kind: 'clear' };
interface Common { path: string; reader: VaultReader; coordinator: VaultMutationCoordinator; projectsDirectory?: string; maxBytes?: number; }
export type UpdateProjectLinkedFoldersOptions = Common & { project: { id: string; source: SourceRef }; mutation: ProjectLinkedFoldersMutation };
export type ProjectLinkedFoldersMutationOutcome = VaultMutationOutcome | { ok: true; noOp: true; path: string; revision: string } | { ok: false; reason: SourcePatchFailureReason | 'invalid-provenance' | 'invalid-value' | 'binary-read-unavailable' | 'missing' };
function validDirectory(directory: string): boolean { return typeof directory === 'string' && directory.length > 0 && directory.length <= 260 && !directory.startsWith('/') && !/^[A-Za-z]:\//.test(directory) && directory.replaceAll('\\', '/').split('/').every((part) => part.length > 0 && part !== '.' && part !== '..'); }
function validSource(source: unknown, directory: string): source is SourceRef { if (typeof source !== 'object' || source === null) return false; const s = source as Partial<SourceRef>; if (s.kind !== 'project' || typeof s.path !== 'string' || s.path.length === 0 || s.path.length > 260 || typeof s.revision !== 'string' || s.revision.length === 0 || s.revision.length > 400) return false; const path = s.path.replaceAll('\\', '/'); const prefix = `${directory.replaceAll('\\', '/')}/`; if (!path.startsWith(prefix) || path.split('/').some((part) => !part || part === '.' || part === '..')) return false; const parts = path.slice(prefix.length).split('/'); return (parts.length === 1 && parts[0]!.toLowerCase().endsWith('.md')) || (parts.length === 2 && parts[1]!.toLowerCase() === 'index.md'); }
function validMutation(mutation: ProjectLinkedFoldersMutation): boolean { if (mutation.kind === 'clear') return true; if (!Array.isArray(mutation.folders) || mutation.folders.length > 256) return false; let total = 0; const seen = new Set<string>(); for (const folder of mutation.folders) { if (!folder || typeof folder.path !== 'string' || folder.path.length === 0 || folder.path.length > 4096 || /[\u0000-\u001F\u007F\r\n]/u.test(folder.path) || (folder.name !== undefined && (typeof folder.name !== 'string' || folder.name.length === 0 || folder.name.length > 4096 || /[\u0000-\u001F\u007F\r\n]/u.test(folder.name)))) return false; const key = folder.path.replaceAll('\\', '/'); if (seen.has(key)) return false; seen.add(key); total += folder.path.length + (folder.name?.length ?? 0); } return total <= 128 * 1024; }

/** Explicit preferred linkedFolders set/clear; legacy encodings fail closed. */
export async function updateProjectLinkedFolders(options: UpdateProjectLinkedFoldersOptions): Promise<ProjectLinkedFoldersMutationOutcome> {
  const raw = (options as unknown as { mutation?: { kind?: unknown } }).mutation; if (!raw || (raw.kind !== 'set' && raw.kind !== 'clear')) return { ok: false, reason: 'field-not-allowed' };
  const directory = (options.projectsDirectory ?? 'Proxima/projects').replaceAll('\\', '/'); if (!validDirectory(directory) || typeof options.project !== 'object' || options.project === null || typeof options.project.id !== 'string' || options.project.id.length === 0 || options.project.id.length > 200 || !validSource(options.project.source, directory)) return { ok: false, reason: 'invalid-provenance' }; if (typeof options.path !== 'string' || options.path.replaceAll('\\', '/') !== options.project.source.path.replaceAll('\\', '/')) return { ok: false, reason: 'invalid-provenance' }; if (!validMutation(options.mutation)) return { ok: false, reason: 'invalid-value' }; if (typeof options.reader.readBinary !== 'function') return { ok: false, reason: 'binary-read-unavailable' };
  const maxBytes = Math.max(1, Math.floor(options.maxBytes ?? 4 * 1024 * 1024)); let file; try { file = await options.reader.readBinary(options.path, maxBytes); } catch { return { ok: false, reason: 'missing' }; } if (file.bytes.byteLength > maxBytes) return { ok: false, reason: 'source-too-large' };
  const patch = options.mutation.kind === 'set' ? planProjectLinkedFoldersSet(file.bytes, options.mutation.folders, maxBytes) : planProjectLinkedFoldersRemove(file.bytes, maxBytes); if (!patch.ok && patch.reason === 'target-missing' && options.mutation.kind === 'clear') return { ok: true, noOp: true, path: options.path, revision: file.revision }; if (!patch.ok) return patch; return options.coordinator.execute({ kind: 'update', path: options.path, bytes: patch.bytes, expectedRevision: options.project.source.revision });
}
